// grammar-units.js — Question bank for Unit 8 (Appearance) and Unit 9 (Entertainment)
// Source: TAGT 2 (Life A2-B1) Units 8 & 9 — National Geographic Learning
// 200 questions total (100 per unit) across vocabulary, grammar, pronunciation

const GRAMMAR_UNITS = [
    {
        id: 'unit8',
        name: 'Unit 8: Appearance',
        icon: '👔',
        color: '#FF9F1C',
        description: 'Clothes • Face & body • Present continuous • have got',
        questions: [
            // ════════ VOCABULARY: CLOTHES (15) ════════
            { id: 'u8-1',  type: 'vocabulary', topic: 'clothes',
              q: 'What do you wear on your feet to play sports?',
              options: ['Trousers', 'Trainers', 'Tie', 'Top'], correct: 1,
              explanation: '"Trainers" (US: sneakers) are athletic shoes worn for sports. Trousers cover the legs.' },
            { id: 'u8-2',  type: 'vocabulary', topic: 'clothes',
              q: 'A businessman often wears a ___ to work.',
              options: ['suit', 'shorts', 'leggings', 'T-shirt'], correct: 0,
              explanation: 'A "suit" is a matching jacket and trousers worn for formal/business occasions.' },
            { id: 'u8-3',  type: 'vocabulary', topic: 'clothes',
              q: 'It\'s very sunny. I need my ___.',
              options: ['scarf', 'sunglasses', 'belt', 'socks'], correct: 1,
              explanation: '"Sunglasses" are dark glasses that protect your eyes from bright sunlight.' },
            { id: 'u8-4',  type: 'vocabulary', topic: 'clothes',
              q: 'Which item is worn around the waist to hold trousers up?',
              options: ['Tie', 'Belt', 'Scarf', 'Shoes'], correct: 1,
              explanation: 'A "belt" is a strap, usually with a buckle, worn around the waist.' },
            { id: 'u8-5',  type: 'vocabulary', topic: 'clothes',
              q: 'It\'s cold outside. You should wear a ___.',
              options: ['T-shirt', 'shorts', 'coat', 'tie'], correct: 2,
              explanation: 'A "coat" is heavy outerwear for cold weather. T-shirts and shorts are for warm weather.' },
            { id: 'u8-6',  type: 'vocabulary', topic: 'clothes',
              q: 'Nurses, police, and pilots all wear a ___ at work.',
              options: ['dress', 'uniform', 'jeans', 'jacket'], correct: 1,
              explanation: 'A "uniform" is special matching clothing for a job. Jeans and dresses are casual.' },
            { id: 'u8-7',  type: 'vocabulary', topic: 'clothes',
              q: 'Which item is tight stretchy trousers, often worn for exercise?',
              options: ['Leggings', 'Shorts', 'Skirt', 'Suit'], correct: 0,
              explanation: '"Leggings" are tight, stretchy trousers, usually worn for sport or casual wear.' },
            { id: 'u8-8',  type: 'vocabulary', topic: 'clothes',
              q: 'A long piece of cloth worn around the neck for warmth is a ___.',
              options: ['tie', 'belt', 'scarf', 'shirt'], correct: 2,
              explanation: 'A "scarf" is wrapped around the neck for warmth. A "tie" is more formal and shorter.' },
            { id: 'u8-9',  type: 'vocabulary', topic: 'clothes',
              q: 'What are short trousers for hot weather called?',
              options: ['Shorts', 'Skirt', 'Socks', 'Suit'], correct: 0,
              explanation: '"Shorts" are short trousers. A "skirt" is one piece for women, usually worn with no legs.' },
            { id: 'u8-10', type: 'vocabulary', topic: 'clothes',
              q: 'A woman wore a beautiful blue ___ to the wedding.',
              options: ['suit', 'dress', 'jeans', 'tie'], correct: 1,
              explanation: 'A "dress" is a one-piece garment worn by women, often for special occasions.' },
            { id: 'u8-11', type: 'vocabulary', topic: 'clothes',
              q: 'You wear ___ on your feet under your shoes.',
              options: ['shorts', 'socks', 'scarf', 'sunglasses'], correct: 1,
              explanation: '"Socks" cover your feet inside your shoes. They protect your feet and keep them warm.' },
            { id: 'u8-12', type: 'vocabulary', topic: 'clothes',
              q: 'A casual blue trouser made of denim is called ___.',
              options: ['leggings', 'jeans', 'shorts', 'suit'], correct: 1,
              explanation: '"Jeans" are casual trousers made of denim — very common worldwide.' },
            { id: 'u8-13', type: 'vocabulary', topic: 'clothes',
              q: 'A short-sleeved cotton top with no buttons is called a ___.',
              options: ['shirt', 'T-shirt', 'jacket', 'coat'], correct: 1,
              explanation: 'A "T-shirt" has no buttons or collar. A "shirt" usually has buttons and a collar.' },
            { id: 'u8-14', type: 'vocabulary', topic: 'clothes',
              q: 'Which of these is worn by women, hanging from the waist down?',
              options: ['Skirt', 'Tie', 'Belt', 'Socks'], correct: 0,
              explanation: 'A "skirt" hangs from the waist; it covers the lower body but is open at the bottom.' },
            { id: 'u8-15', type: 'vocabulary', topic: 'clothes',
              q: 'What do you carry your books or laptop in?',
              options: ['Suit', 'Tie', 'Bag', 'Belt'], correct: 2,
              explanation: 'A "bag" is a container with handles or straps used to carry things.' },

            // ════════ VOCABULARY: FACE & BODY (15) ════════
            { id: 'u8-16', type: 'vocabulary', topic: 'face & body',
              q: 'You hear with your ___.',
              options: ['eyes', 'ears', 'mouth', 'nose'], correct: 1,
              explanation: '"Ears" are for hearing. "Eyes" are for seeing.' },
            { id: 'u8-17', type: 'vocabulary', topic: 'face & body',
              q: 'You speak with your ___.',
              options: ['hands', 'feet', 'mouth', 'shoulders'], correct: 2,
              explanation: 'You speak using your "mouth" (where your tongue and teeth are).' },
            { id: 'u8-18', type: 'vocabulary', topic: 'face & body',
              q: 'Hair on a man\'s face (around the chin) is called a ___.',
              options: ['beard', 'mouth', 'eye', 'shoulder'], correct: 0,
              explanation: 'A "beard" is the hair that grows on a man\'s chin and cheeks.' },
            { id: 'u8-19', type: 'vocabulary', topic: 'face & body',
              q: 'You write and hold things with your ___.',
              options: ['feet', 'hands', 'shoulders', 'mouth'], correct: 1,
              explanation: '"Hands" have fingers and are used to hold and write.' },
            { id: 'u8-20', type: 'vocabulary', topic: 'face & body',
              q: 'You walk on your ___.',
              options: ['hands', 'shoulders', 'feet', 'arms'], correct: 2,
              explanation: '"Feet" are at the bottom of your legs (singular: foot). You walk on them.' },
            { id: 'u8-21', type: 'vocabulary', topic: 'face & body',
              q: 'Your ___ connect your hands to your shoulders.',
              options: ['legs', 'arms', 'feet', 'eyes'], correct: 1,
              explanation: '"Arms" go from your shoulder to your hand. "Legs" connect feet to hips.' },
            { id: 'u8-22', type: 'vocabulary', topic: 'face & body',
              q: 'Which is on the top of your body and contains your brain?',
              options: ['Head', 'Foot', 'Hand', 'Leg'], correct: 0,
              explanation: 'Your "head" is on top of your body and contains your brain, eyes, ears, nose, and mouth.' },
            { id: 'u8-23', type: 'vocabulary', topic: 'face & body',
              q: 'You carry a heavy bag on your ___.',
              options: ['mouth', 'eye', 'shoulder', 'foot'], correct: 2,
              explanation: 'Your "shoulder" is where the arm joins the body — perfect for hanging a bag.' },
            { id: 'u8-24', type: 'vocabulary', topic: 'face & body',
              q: 'My sister has long, dark ___ and blue eyes.',
              options: ['mouth', 'hair', 'ears', 'feet'], correct: 1,
              explanation: '"Hair" grows on your head. We describe it by length and colour ("long, dark hair").' },
            { id: 'u8-25', type: 'vocabulary', topic: 'face & body',
              q: 'In winter, gloves keep your ___ warm.',
              options: ['head', 'feet', 'hands', 'eyes'], correct: 2,
              explanation: 'Gloves are worn on the "hands". A scarf keeps your neck warm; a hat keeps your head warm.' },
            { id: 'u8-26', type: 'vocabulary', topic: 'face & body',
              q: '"Ralph is growing his ___; it covers his ___."',
              options: ['hair / hands', 'beard / mouth', 'eyes / nose', 'feet / arms'], correct: 1,
              explanation: 'A "beard" grows on the lower face and can cover the "mouth" if it gets long.' },
            { id: 'u8-27', type: 'vocabulary', topic: 'face & body',
              q: 'Climbers need strong ___ and ___ for the mountain.',
              options: ['eyes / mouth', 'arms / legs', 'ears / shoulders', 'beard / hair'], correct: 1,
              explanation: 'Climbing requires strong "arms" (to pull) and "legs" (to push up).' },
            { id: 'u8-28', type: 'vocabulary', topic: 'face & body',
              q: '"That music is loud! My ___ are aching!"',
              options: ['feet', 'eyes', 'ears', 'hands'], correct: 2,
              explanation: 'Loud sound hurts your "ears" (the part of the body that hears).' },
            { id: 'u8-29', type: 'vocabulary', topic: 'face & body',
              q: 'Twins have similar ___.',
              options: ['hands and feet', 'hair and eyes', 'shoulders and beard', 'mouth and ears'], correct: 1,
              explanation: 'When describing twins\' looks, we usually mention "hair" colour and "eye" colour first.' },
            { id: 'u8-30', type: 'vocabulary', topic: 'face & body',
              q: 'A ring is worn on your ___.',
              options: ['hand (finger)', 'shoulder', 'foot', 'eye'], correct: 0,
              explanation: 'Rings go on the fingers of your "hand". A bracelet goes around the wrist.' },

            // ════════ PRONUNCIATION: STRESS DIFFERENCE (10) ════════
            { id: 'u8-31', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable from the others.',
              options: ['trouser', 'trainer', 'parade', 'costume'], correct: 2,
              explanation: '"Parade" /pəˈreɪd/ is stressed on the SECOND syllable. The others are stressed on the FIRST: TROUser, TRAINer, COStume.' },
            { id: 'u8-32', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['jacket', 'beard', 'uniform', 'mountain'], correct: 1,
              explanation: '"Beard" is one syllable so the stress is uniform. The others have FIRST-syllable stress: JACKet, UNiform, MOUNtain. Trick: "beard" can\'t mismatch in stress because it\'s monosyllabic — so by elimination none of the multisyllable words mismatch. Re-read carefully: this question highlights that in lists like these, single-syllable words don\'t have a "different" stress pattern by definition.' },
            { id: 'u8-33', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['present (gift)', 'present (verb: to present)', 'practice', 'pretty'], correct: 1,
              explanation: 'Many noun/verb pairs in English shift stress: PREsent (noun) vs preSENT (verb). The verb form is stressed on the second syllable.' },
            { id: 'u8-34', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['fashion', 'famous', 'design', 'workers'], correct: 2,
              explanation: '"Design" /dɪˈzaɪn/ has stress on the second syllable. The others are first-syllable stressed: FAshion, FAmous, WORKers.' },
            { id: 'u8-35', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['photo', 'photograph', 'photographer', 'photographic'], correct: 2,
              explanation: 'Stress shifts in this word family: PHOto, PHOtograph, phoTOGrapher (2nd), photoGRAPHic (3rd). "Photographer" is stressed on the SECOND syllable; the others differ.' },
            { id: 'u8-36', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['fashion', 'jacket', 'designer', 'jewellery'], correct: 2,
              explanation: '"Designer" /dɪˈzaɪnər/ is stressed on the SECOND syllable. Others stress the FIRST: FAshion, JACKet, JEWellery.' },
            { id: 'u8-37', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['picture', 'colourful', 'unusual', 'painting'], correct: 2,
              explanation: '"Unusual" /ʌnˈjuːʒuəl/ is stressed on the SECOND syllable. The others stress the FIRST: PICture, COlourful, PAINTing.' },
            { id: 'u8-38', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['costume', 'normal', 'before', 'shoulder'], correct: 2,
              explanation: '"Before" /bɪˈfɔːr/ is stressed on the SECOND syllable. Others stress the FIRST: COStume, NORmal, SHOULder.' },
            { id: 'u8-39', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['important', 'amazing', 'wonderful', 'incredible'], correct: 2,
              explanation: 'Three of these have SECOND-syllable stress: imPORTant, aMAZing, inCREDible. But "WONderful" /ˈwʌndəfʊl/ is stressed on the FIRST syllable.' },
            { id: 'u8-40', type: 'pronunciation', topic: 'word stress',
              q: 'Which word has stress on a DIFFERENT syllable?',
              options: ['Philippines', 'environment', 'photographer', 'community'], correct: 0,
              explanation: '"PHIlippines" is stressed on the FIRST syllable. Others stress the SECOND: enVIRonment, phoTOGrapher, comMUnity.' },

            // ════════ PRONUNCIATION: /s/ vs /ʃ/ + silent letters + sound spelling (10) ════════
            { id: 'u8-41', type: 'pronunciation', topic: '/s/ vs /ʃ/',
              q: 'Which word has the /ʃ/ ("sh") sound?',
              options: ['suit', 'socks', 'shoes', 'sunglasses'], correct: 2,
              explanation: '"Shoes" starts with the /ʃ/ sound. The others start with /s/.' },
            { id: 'u8-42', type: 'pronunciation', topic: '/s/ vs /ʃ/',
              q: 'Which word has the /s/ sound (NOT /ʃ/)?',
              options: ['shirt', 'shorts', 'skirt', 'shop'], correct: 2,
              explanation: '"Skirt" starts with /s/. "Shirt", "shorts", "shop" all start with /ʃ/ (the "sh" sound).' },
            { id: 'u8-43', type: 'pronunciation', topic: 'silent letters',
              q: 'Which letter is SILENT in "blonde"?',
              options: ['b', 'l', 'o', 'e'], correct: 3,
              explanation: 'In "blonde" /blɒnd/, the final "e" is silent — it does not make a sound.' },
            { id: 'u8-44', type: 'pronunciation', topic: 'silent letters',
              q: 'Which letter is SILENT in "listening"?',
              options: ['l', 't', 'n', 'g'], correct: 1,
              explanation: 'In "listening" /ˈlɪsənɪŋ/, the "t" is silent. Same for "listen", "fasten", "soften".' },
            { id: 'u8-45', type: 'pronunciation', topic: 'silent letters',
              q: 'Which letter is SILENT in "everyday"?',
              options: ['v', 'e (last)', 'r', 'd'], correct: 1,
              explanation: 'In "everyday" /ˈevrideɪ/, the middle "e" can be silent (the word sounds like "EVryday"). Some letters are commonly skipped.' },
            { id: 'u8-46', type: 'pronunciation', topic: 'sound spelling',
              q: 'Which word has the same vowel sound as "head" /e/?',
              options: ['shoes', 'feet', 'leg', 'eye'], correct: 2,
              explanation: '"Head" and "leg" both have the /e/ short-e sound. "Shoes"=/uː/, "feet"=/iː/, "eye"=/aɪ/.' },
            { id: 'u8-47', type: 'pronunciation', topic: 'sound spelling',
              q: 'Which word has the same vowel sound as "shoes" /uː/?',
              options: ['suit', 'tie', 'leg', 'ears'], correct: 0,
              explanation: '"Shoes" /ʃuːz/ and "suit" /suːt/ both have the long /uː/ sound.' },
            { id: 'u8-48', type: 'pronunciation', topic: 'sound spelling',
              q: 'Which word has the same vowel sound as "beard" /ɪə/?',
              options: ['ears', 'tie', 'leg', 'coat'], correct: 0,
              explanation: '"Beard" /bɪəd/ and "ears" /ɪəz/ both have the /ɪə/ diphthong (in British English).' },
            { id: 'u8-49', type: 'pronunciation', topic: 'sound spelling',
              q: 'Which word has the same vowel sound as "eye" /aɪ/?',
              options: ['tie', 'feet', 'ears', 'coat'], correct: 0,
              explanation: '"Eye" /aɪ/ and "tie" /taɪ/ both have the /aɪ/ diphthong sound.' },
            { id: 'u8-50', type: 'pronunciation', topic: 'sound spelling',
              q: 'Which word has the same vowel sound as "nose" /əʊ/?',
              options: ['coat', 'leg', 'ears', 'eye'], correct: 0,
              explanation: '"Nose" /nəʊz/ and "coat" /kəʊt/ both have the /əʊ/ diphthong.' },

            // ════════ GRAMMAR: PRESENT CONTINUOUS (15) ════════
            { id: 'u8-51', type: 'grammar', topic: 'present continuous',
              q: 'She ___ a beautiful red dress today.',
              options: ['wear', 'wears', 'is wearing', 'wore'], correct: 2,
              explanation: 'Present continuous (am/is/are + verb-ing) is used for actions happening NOW or AROUND NOW. "Today" signals current time.' },
            { id: 'u8-52', type: 'grammar', topic: 'present continuous',
              q: 'I ___ at the moment, can you call back later?',
              options: ['drive', 'driving', 'am driving', 'drives'], correct: 2,
              explanation: '"At the moment" is a present continuous time expression. The structure is: subject + am/is/are + verb-ing.' },
            { id: 'u8-53', type: 'grammar', topic: 'present continuous',
              q: 'They ___ in the office today.',
              options: ['don\'t work', 'aren\'t working', 'isn\'t working', 'not working'], correct: 1,
              explanation: 'Negative present continuous: subject + am/is/are + NOT + verb-ing. With "they" we use "are not" → "aren\'t working".' },
            { id: 'u8-54', type: 'grammar', topic: 'present continuous',
              q: 'He ___ a brown rucksack.',
              options: ['hold', 'is holding', 'are holding', 'holds'], correct: 1,
              explanation: '"He" takes "is" + verb-ing. "Holds" is present simple (habits). Here we describe what he\'s doing right now.' },
            { id: 'u8-55', type: 'grammar', topic: 'present continuous',
              q: 'The company ___ any money at the moment.',
              options: ['don\'t make', 'isn\'t making', 'aren\'t making', 'doesn\'t make'], correct: 1,
              explanation: '"The company" is singular ("it"), so we use "isn\'t making" (is + not + verb-ing).' },
            { id: 'u8-56', type: 'grammar', topic: 'present continuous',
              q: '___ you ___ this bag?',
              options: ['Are / buying', 'Do / buying', 'Is / buy', 'Are / buy'], correct: 0,
              explanation: 'Present continuous question: Are/Is + subject + verb-ing? With "you" → "Are you buying?"' },
            { id: 'u8-57', type: 'grammar', topic: 'present continuous',
              q: '"What ___ you ___?" "I\'m reading a book."',
              options: ['do / do', 'are / doing', 'are / do', 'do / doing'], correct: 1,
              explanation: 'Wh-question in present continuous: What/Where/Why + are/is + subject + verb-ing? "What are you doing?"' },
            { id: 'u8-58', type: 'grammar', topic: 'present continuous',
              q: '"Is she buying that bag?" "Yes, ___."',
              options: ['she does', 'she is', 'she\'s', 'she buys'], correct: 1,
              explanation: 'Short answers to present continuous questions: Yes, she IS / No, she ISN\'T. Don\'t use "she\'s" in short answers.' },
            { id: 'u8-59', type: 'grammar', topic: 'present continuous',
              q: 'Look! It ___ outside.',
              options: ['rains', 'is raining', 'rain', 'are raining'], correct: 1,
              explanation: '"Look!" signals NOW. With "it" (weather), we use "is raining" — present continuous for an action happening now.' },
            { id: 'u8-60', type: 'grammar', topic: 'present continuous',
              q: 'Rags2Riches ___ today.',
              options: ['grow', 'growing', 'is growing', 'grows'], correct: 2,
              explanation: 'For changing actions (a company growing), we use present continuous: "is growing".' },
            { id: 'u8-61', type: 'grammar', topic: 'present continuous',
              q: 'I\'m on holiday this week. I ___.',
              options: ['don\'t work', 'am not working', 'not work', 'isn\'t working'], correct: 1,
              explanation: '"This week" is a present continuous time expression for temporary situations. With "I" → "am not working".' },
            { id: 'u8-62', type: 'grammar', topic: 'present continuous',
              q: 'He looks cold. He ___ a coat.',
              options: ['doesn\'t wear', 'isn\'t wearing', 'aren\'t wearing', 'don\'t wear'], correct: 1,
              explanation: 'Description of his current state ("looks cold") → present continuous negative. "He" + "isn\'t wearing".' },
            { id: 'u8-63', type: 'grammar', topic: 'present continuous',
              q: 'Tom Ford ___ his clothes this year?',
              options: ['Is / designing', 'Does / designing', 'Are / design', 'Do / designing'], correct: 0,
              explanation: '"This year" suggests an ongoing/temporary action. Present continuous question: "Is Tom Ford designing...?"' },
            { id: 'u8-64', type: 'grammar', topic: 'present continuous',
              q: 'The two women in the photo ___ bags.',
              options: ['are making', 'is making', 'make', 'makes'], correct: 0,
              explanation: '"In the photo" → action you can SEE happening. Plural subject "two women" → "are making".' },
            { id: 'u8-65', type: 'grammar', topic: 'present continuous',
              q: 'We ___ more workers.',
              options: ['training', 'is training', 'are training', 'trains'], correct: 2,
              explanation: 'Plural subject "we" → "are" + verb-ing. The continuous form shows an action around the present time.' },

            // ════════ GRAMMAR: PRESENT SIMPLE vs PRESENT CONTINUOUS (15) ════════
            { id: 'u8-66', type: 'grammar', topic: 'present simple vs continuous',
              q: 'At the moment, I ___ in Asia.',
              options: ['travel', 'am travelling', 'travels', 'am travel'], correct: 1,
              explanation: '"At the moment" → present continuous. Use "am/is/are + verb-ing" for actions happening now.' },
            { id: 'u8-67', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Usually, he ___ to the gym during the week.',
              options: ['don\'t go', 'isn\'t going', 'doesn\'t go', 'aren\'t going'], correct: 2,
              explanation: '"Usually" → habit/routine → present SIMPLE. With "he" → "doesn\'t go".' },
            { id: 'u8-68', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Today she ___ an important customer.',
              options: ['visits', 'is visiting', 'visit', 'visited'], correct: 1,
              explanation: '"Today" can take present continuous to emphasize the action is happening today specifically. "Is visiting" works here.' },
            { id: 'u8-69', type: 'grammar', topic: 'present simple vs continuous',
              q: 'My sister ___ clothes and fashion.',
              options: ['like', 'likes', 'is liking', 'liking'], correct: 1,
              explanation: '"Like" is a STATE verb — we don\'t use it in continuous form. Use present simple: "She likes...".' },
            { id: 'u8-70', type: 'grammar', topic: 'present simple vs continuous',
              q: 'These days, the cost of clothes ___ up.',
              options: ['go', 'goes', 'is going', 'are going'], correct: 2,
              explanation: '"These days" suggests a current trend/changing situation → present continuous. Singular subject "cost" → "is going up".' },
            { id: 'u8-71', type: 'grammar', topic: 'present simple vs continuous',
              q: 'She ___ on holiday very often.',
              options: ['doesn\'t go', 'isn\'t going', 'don\'t go', 'aren\'t going'], correct: 0,
              explanation: '"Very often" → frequency → routine → present simple negative. With "she" → "doesn\'t go".' },
            { id: 'u8-72', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Joe ___ from home this morning.',
              options: ['works', 'is working', 'work', 'are working'], correct: 1,
              explanation: '"This morning" is a temporary situation. Use present continuous: "is working from home".' },
            { id: 'u8-73', type: 'grammar', topic: 'present simple vs continuous',
              q: 'My father ___ from New York but he ___ in Philadelphia.',
              options: ['comes / lives', 'is coming / is living', 'comes / is living', 'is coming / lives'], correct: 0,
              explanation: 'Origin (where you come FROM) and where you LIVE are facts → present simple. Note: "comes from" = origin, not a current journey.' },
            { id: 'u8-74', type: 'grammar', topic: 'present simple vs continuous',
              q: '"Do you normally wear a uniform?" "Yes, I do, but today I ___ a T-shirt and jeans."',
              options: ['wear', 'wears', 'am wearing', 'wore'], correct: 2,
              explanation: '"Today" + temporary action → present continuous. "I am wearing" describes what\'s on now (different from the routine).' },
            { id: 'u8-75', type: 'grammar', topic: 'present simple vs continuous',
              q: '"Is it raining in your town today?" "No, ___."',
              options: ['it doesn\'t', 'it isn\'t', 'it is', 'it doesn\'t rain'], correct: 1,
              explanation: 'Short answer to a present continuous question: "Yes, it is" / "No, it isn\'t".' },
            { id: 'u8-76', type: 'grammar', topic: 'present simple vs continuous',
              q: 'The sun ___ in the east every day.',
              options: ['is rising', 'rises', 'rise', 'are rising'], correct: 1,
              explanation: 'A scientific fact / always-true statement → present simple. With "sun" (it) → "rises".' },
            { id: 'u8-77', type: 'grammar', topic: 'present simple vs continuous',
              q: '"Where do you come from?" "Spain, but I ___ in England for a year."',
              options: ['study', 'am studying', 'studied', 'studies'], correct: 1,
              explanation: '"For a year" is a temporary period → present continuous. "I am studying" indicates a temporary current arrangement.' },
            { id: 'u8-78', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Rajo Laurel normally ___ clothes for the rich and famous, but at the moment, he ___ bags.',
              options: ['designs / is designing', 'is designing / designs', 'design / is designing', 'designs / designs'], correct: 0,
              explanation: '"Normally" → routine → present simple ("designs"). "At the moment" → temporary → present continuous ("is designing").' },
            { id: 'u8-79', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Water ___ at 100°C.',
              options: ['is boiling', 'boils', 'boil', 'are boiling'], correct: 1,
              explanation: 'A scientific fact → present simple. With "water" (uncountable, treated as it) → "boils".' },
            { id: 'u8-80', type: 'grammar', topic: 'present simple vs continuous',
              q: 'Sorry, I can\'t talk now. I ___ dinner.',
              options: ['make', 'am making', 'makes', 'making'], correct: 1,
              explanation: 'Right now (you can\'t talk) → present continuous: "am making".' },

            // ════════ GRAMMAR: HAVE GOT (10) ════════
            { id: 'u8-81', type: 'grammar', topic: 'have got',
              q: 'I ___ one sister and two brothers.',
              options: ['has got', 'have got', 'got', 'is got'], correct: 1,
              explanation: '"Have got" is used for possession/family/appearance. With "I" → "have got" (NOT "has got").' },
            { id: 'u8-82', type: 'grammar', topic: 'have got',
              q: 'He ___ a beard.',
              options: ['have got', 'has got', 'has\'t got', 'have not got'], correct: 1,
              explanation: 'With "he/she/it", use "has got". For appearance (beard), "has got" is natural.' },
            { id: 'u8-83', type: 'grammar', topic: 'have got',
              q: 'The two sisters ___ the same dress.',
              options: ['have got', 'has got', 'is got', 'got'], correct: 0,
              explanation: 'Plural subject "two sisters" → "have got" (not "has got").' },
            { id: 'u8-84', type: 'grammar', topic: 'have got',
              q: 'He ___ a hat. (negative)',
              options: ['hasn\'t got', 'haven\'t got', 'isn\'t got', 'doesn\'t got'], correct: 0,
              explanation: 'Negative with "he" → "hasn\'t got" (= has not got).' },
            { id: 'u8-85', type: 'grammar', topic: 'have got',
              q: '___ they got a car?',
              options: ['Has', 'Have', 'Do', 'Are'], correct: 1,
              explanation: 'Question with "they" → "Have they got...?" The answer is "Yes, they have / No, they haven\'t".' },
            { id: 'u8-86', type: 'grammar', topic: 'have got',
              q: '"Have they got a car?" "Yes, ___."',
              options: ['they have', 'they got', 'they do', 'they\'ve'], correct: 0,
              explanation: 'Short answer: Yes, they HAVE / No, they HAVEN\'T. Avoid "they\'ve" in short answers.' },
            { id: 'u8-87', type: 'grammar', topic: 'have got',
              q: 'In "He\'s tall" the \'s means ___.',
              options: ['is', 'has', 'us', 'his'], correct: 0,
              explanation: '"He\'s tall" = "He IS tall" (description with "be"). When followed by an adjective alone → "is".' },
            { id: 'u8-88', type: 'grammar', topic: 'have got',
              q: 'In "He\'s got long hair" the \'s means ___.',
              options: ['is', 'has', 'us', 'was'], correct: 1,
              explanation: '"He\'s got" = "He HAS got". "Got" follows "has", not "is".' },
            { id: 'u8-89', type: 'grammar', topic: 'have got',
              q: 'She ___ blue eyes.',
              options: ['have got', 'has got', 'is got', 'are got'], correct: 1,
              explanation: 'Appearance (eye colour) with "she" → "has got blue eyes".' },
            { id: 'u8-90', type: 'grammar', topic: 'have got',
              q: '___ you got any sisters?',
              options: ['Has', 'Have', 'Do', 'Is'], correct: 1,
              explanation: 'Question: with "you" → "Have you got any sisters?"' },

            // ════════ READING / WORD FOCUS (10) ════════
            { id: 'u8-91', type: 'vocabulary', topic: 'word focus: like',
              q: '"There are blue toys LIKE robots and dinosaurs." Here "like" means ___.',
              options: ['love', 'similar to', 'such as', 'enjoy'], correct: 2,
              explanation: 'Here "like" = "such as" (giving examples). It\'s NOT the verb "to love".' },
            { id: 'u8-92', type: 'vocabulary', topic: 'word focus: like',
              q: '"Girls LIKE pink." Here "like" means ___.',
              options: ['similar to', 'such as', 'love / enjoy', 'unlike'], correct: 2,
              explanation: 'When "like" is the main verb (e.g., "Girls like pink"), it means "love / enjoy".' },
            { id: 'u8-93', type: 'vocabulary', topic: 'word focus: like',
              q: 'Many girls were LIKE Seowoo. Here "like" means ___.',
              options: ['such as', 'similar to', 'love', 'unlike'], correct: 1,
              explanation: 'Here "like Seowoo" = "similar to Seowoo" (resembling her).' },
            { id: 'u8-94', type: 'vocabulary', topic: 'festivals',
              q: 'Which adjective means "lots of bright colours"?',
              options: ['quiet', 'colourful', 'boring', 'crowded'], correct: 1,
              explanation: '"Colourful" means full of bright colours.' },
            { id: 'u8-95', type: 'vocabulary', topic: 'festivals',
              q: 'A festival with many people is ___.',
              options: ['quiet', 'crowded', 'boring', 'relaxing'], correct: 1,
              explanation: '"Crowded" means there are many people in one place.' },
            { id: 'u8-96', type: 'vocabulary', topic: 'festivals',
              q: 'A festival you really enjoy is ___.',
              options: ['boring', 'fun', 'noisy', 'quiet'], correct: 1,
              explanation: '"Fun" means enjoyable. "Boring" is the opposite.' },
            { id: 'u8-97', type: 'vocabulary', topic: 'festivals',
              q: 'A place where you can hear loud noises is ___.',
              options: ['quiet', 'noisy', 'relaxing', 'boring'], correct: 1,
              explanation: '"Noisy" means full of loud sounds. "Quiet" is the opposite.' },
            { id: 'u8-98', type: 'vocabulary', topic: 'festivals',
              q: 'Which adjective is the OPPOSITE of "boring"?',
              options: ['quiet', 'noisy', 'exciting', 'crowded'], correct: 2,
              explanation: '"Exciting" means making you feel excited. "Boring" is its opposite.' },
            { id: 'u8-99', type: 'vocabulary', topic: 'photos',
              q: 'When describing a photo, "in the middle" means ___.',
              options: ['on the left', 'at the front', 'in the centre', 'at the back'], correct: 2,
              explanation: '"In the middle" = "in the centre" of the photo (between left and right, top and bottom).' },
            { id: 'u8-100', type: 'vocabulary', topic: 'photos',
              q: 'Which is NOT a position used to describe a photo?',
              options: ['on the left', 'at the back', 'in the middle', 'in the future'], correct: 3,
              explanation: '"In the future" describes time, not position. The others all describe position in a photo.' },

            // ════════ PRONUNCIATION: UNDERLINED LETTER (20) ════════
            // Format: "Choose the word that has the underlined part pronounced differently from the others"
            // Underlined letters are wrapped in <u>...</u> and rendered as HTML.
            { id: 'u8-101', type: 'pronunciation', topic: 'underlined letter (c: /k/ vs /s/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['<u>c</u>oat', '<u>c</u>ottage', '<u>c</u>eiling', '<u>c</u>ostume'], correct: 2,
              explanation: 'In "ceiling" /ˈsiːlɪŋ/ the <u>c</u> sounds /s/. In "coat, cottage, costume" the <u>c</u> sounds /k/. Rule: "c" before e/i/y is /s/; before a/o/u (or a consonant) it is /k/.' },
            { id: 'u8-102', type: 'pronunciation', topic: 'underlined letter (final s: /s/ vs /z/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['shirt<u>s</u>', 'shoe<u>s</u>', 'sock<u>s</u>', 'coat<u>s</u>'], correct: 1,
              explanation: 'In "shoes" /ʃuːz/ the final <u>s</u> sounds /z/ (after a voiced vowel). In "shirts, socks, coats" the final <u>s</u> sounds /s/ (after voiceless /t/, /k/).' },
            { id: 'u8-103', type: 'pronunciation', topic: 'underlined letter (sh vs s)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>sh</u>oes', '<u>sh</u>irt', '<u>s</u>uit', '<u>sh</u>orts'], correct: 2,
              explanation: '"sh" is pronounced /ʃ/ (shoes, shirt, shorts). Plain "s" at the start of "suit" /suːt/ is /s/.' },
            { id: 'u8-104', type: 'pronunciation', topic: 'underlined letter (ea: /e/ vs /ɪə/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['h<u>ea</u>d', 'b<u>ea</u>rd', '<u>ea</u>r', 'h<u>ea</u>r'], correct: 0,
              explanation: '"head" /hed/ has the short /e/ sound. "beard, ear, hear" all have the /ɪə/ diphthong.' },
            { id: 'u8-105', type: 'pronunciation', topic: 'underlined letter (ai: /eɪ/ vs /eə/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['tr<u>ai</u>ners', 'h<u>ai</u>r', 'tr<u>ai</u>n', 'r<u>ai</u>n'], correct: 1,
              explanation: '"hair" /heə(r)/ uses the /eə/ diphthong (the "air" sound). "Trainers, train, rain" all use /eɪ/ (the "ay" sound).' },
            { id: 'u8-106', type: 'pronunciation', topic: 'underlined letter (ou: /aʊ/ vs /əʊ/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['tr<u>ou</u>sers', 'sh<u>ou</u>lder', 'l<u>ou</u>d', 'ar<u>ou</u>nd'], correct: 1,
              explanation: '"shoulder" uses /əʊ/ (like "go"). The others use /aʊ/ (like "now"): trousers, loud, around.' },
            { id: 'u8-107', type: 'pronunciation', topic: 'underlined letter (ow: /aʊ/ vs /əʊ/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['cl<u>ow</u>n', 'br<u>ow</u>n', 'sh<u>ow</u>', 'cr<u>ow</u>d'], correct: 2,
              explanation: '"show" uses /əʊ/ (like "go"). "Clown, brown, crowd" all use /aʊ/ (like "now"). The spelling "ow" can sound either way.' },
            { id: 'u8-108', type: 'pronunciation', topic: 'underlined letter (g: /g/ vs /dʒ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['<u>g</u>love', '<u>g</u>arden', 'lar<u>g</u>e', '<u>g</u>row'], correct: 2,
              explanation: 'In "large" /lɑːdʒ/ the <u>g</u> is /dʒ/ (because of the "e" after it). In "glove, garden, grow" the <u>g</u> is /g/. Rule: "g" before e/i/y is often /dʒ/.' },
            { id: 'u8-109', type: 'pronunciation', topic: 'underlined letter (th: /θ/ vs /ð/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>th</u>ree', '<u>th</u>ank', '<u>th</u>ey', '<u>th</u>ick'], correct: 2,
              explanation: '"they" uses voiced /ð/ (vibrating throat). "Three, thank, thick" use unvoiced /θ/ (no vibration). Both spellings are "th".' },
            { id: 'u8-110', type: 'pronunciation', topic: 'underlined letter (i: /aɪ/ vs /ɪ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['t<u>i</u>e', 'n<u>i</u>ce', 'tw<u>i</u>n', 'l<u>i</u>ke'], correct: 2,
              explanation: '"twin" /twɪn/ has the short /ɪ/. "Tie, nice, like" all use the long /aɪ/.' },
            { id: 'u8-111', type: 'pronunciation', topic: 'underlined letter (oo: /ʊ/ vs /uː/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['f<u>oo</u>t', 'g<u>oo</u>d', 'l<u>oo</u>k', 'm<u>oo</u>n'], correct: 3,
              explanation: 'Some "oo" words use short /ʊ/ (foot, good, look). Others use long /uː/ (moon, food, soon). "Moon" is the odd one here.' },
            { id: 'u8-112', type: 'pronunciation', topic: 'underlined letter (silent t)',
              q: 'In which word is the underlined letter SILENT?',
              options: ['par<u>t</u>y', 'lis<u>t</u>en', 'in<u>t</u>eresting', 'shor<u>t</u>s'], correct: 1,
              explanation: 'In "listen" /ˈlɪsən/ the <u>t</u> is silent. The same is true for "castle, fasten, soften". In "party, interesting, shorts" the <u>t</u> is pronounced.' },
            { id: 'u8-113', type: 'pronunciation', topic: 'underlined letter (silent e)',
              q: 'In which word is the underlined letter SILENT?',
              options: ['blond<u>e</u>', 'her<u>e</u>', 'lat<u>e</u>r', 'm<u>e</u>'], correct: 0,
              explanation: 'In "blonde" the final <u>e</u> is silent. (Compare: "later" has /ə/, "here" has the e contributing to /ɪə/, "me" the e is /iː/.)' },
            { id: 'u8-114', type: 'pronunciation', topic: 'underlined letter (a: /æ/ vs /ɑː/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['h<u>a</u>nd', 'b<u>a</u>g', 'sc<u>a</u>rf', 'h<u>a</u>t'], correct: 2,
              explanation: '"scarf" /skɑːf/ uses the long /ɑː/ sound. "Hand, bag, hat" all use the short /æ/ sound (cat-vowel).' },
            { id: 'u8-115', type: 'pronunciation', topic: 'underlined letter (or: /ɔː/ vs /ɜː/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['sh<u>or</u>t', 'w<u>or</u>k', 'sp<u>or</u>t', 'n<u>or</u>th'], correct: 1,
              explanation: '"work" /wɜːk/ uses the /ɜː/ sound (her-vowel). "Short, sport, north" all use /ɔː/ (door-vowel).' },
            { id: 'u8-116', type: 'pronunciation', topic: 'underlined letter (wh: /w/ vs /h/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>wh</u>at', '<u>wh</u>en', '<u>wh</u>o', '<u>wh</u>ere'], correct: 2,
              explanation: 'In "who" /huː/ the <u>w</u> is silent — only /h/ remains. "What, when, where" all start with /w/.' },
            { id: 'u8-117', type: 'pronunciation', topic: 'underlined letter (y: /aɪ/ vs /i/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['happ<u>y</u>', 'm<u>y</u>', 'cr<u>y</u>', 'tr<u>y</u>'], correct: 0,
              explanation: '"happy" ends with the short /i/ sound. "My, cry, try" all use the diphthong /aɪ/.' },
            { id: 'u8-118', type: 'pronunciation', topic: 'underlined letter (i: /aɪ/ vs /ɜː/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['n<u>i</u>ne', 'n<u>i</u>ght', 'sk<u>i</u>rt', 'l<u>i</u>fe'], correct: 2,
              explanation: '"skirt" /skɜːt/ uses the /ɜː/ sound. "Nine, night, life" all use the diphthong /aɪ/.' },
            { id: 'u8-119', type: 'pronunciation', topic: 'underlined letter (s: /s/ vs /z/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['i<u>s</u>', 'thi<u>s</u>', 'ha<u>s</u>', 'wa<u>s</u>'], correct: 1,
              explanation: '"this" /ðɪs/ ends with unvoiced /s/. "is, has, was" all end with voiced /z/. Tip: function words like is/was/has/does end in /z/; demonstratives this/thus/yes end in /s/.' },
            { id: 'u8-120', type: 'pronunciation', topic: 'underlined letter (a: /eɪ/ vs /æ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['m<u>a</u>ke', 'f<u>a</u>ce', 'm<u>a</u>sk', 't<u>a</u>ke'], correct: 2,
              explanation: '"mask" /mɑːsk/ (BrE) or /mæsk/ (AmE) is short. "Make, face, take" all have the long /eɪ/ sound (ay-sound) because of the silent "e" at the end.' }
        ]
    },
    {
        id: 'unit9',
        name: 'Unit 9: Entertainment',
        icon: '🎬',
        color: '#9b59b6',
        description: 'Films • TV • Nature in art • be going to • Sense verbs',
        questions: [
            // ════════ VOCABULARY: FILMS (12) ════════
            { id: 'u9-1',  type: 'vocabulary', topic: 'films',
              q: 'A film with cartoons (drawn or computer-animated images) is called a(n) ___.',
              options: ['comedy', 'animation', 'thriller', 'horror'], correct: 1,
              explanation: '"Animation" is a film made with drawings or computer images, not live actors.' },
            { id: 'u9-2',  type: 'vocabulary', topic: 'films',
              q: 'A funny film that makes you laugh is a ___.',
              options: ['horror', 'comedy', 'documentary', 'thriller'], correct: 1,
              explanation: '"Comedy" is a film designed to make you laugh.' },
            { id: 'u9-3',  type: 'vocabulary', topic: 'films',
              q: 'A film about real people, animals, or events is a ___.',
              options: ['documentary', 'fantasy', 'thriller', 'science fiction'], correct: 0,
              explanation: '"Documentary" films show real life — real people, animals, or events.' },
            { id: 'u9-4',  type: 'vocabulary', topic: 'films',
              q: 'A film with magic, dragons, or imaginary worlds is ___.',
              options: ['horror', 'comedy', 'fantasy', 'documentary'], correct: 2,
              explanation: '"Fantasy" films include magical or imaginary elements like dragons and wizards.' },
            { id: 'u9-5',  type: 'vocabulary', topic: 'films',
              q: 'A scary film that makes you frightened is a ___ film.',
              options: ['comedy', 'horror', 'romantic', 'animation'], correct: 1,
              explanation: '"Horror" films are designed to scare and frighten the viewer.' },
            { id: 'u9-6',  type: 'vocabulary', topic: 'films',
              q: 'A film about love, often funny, is a ___.',
              options: ['romantic comedy', 'thriller', 'horror', 'documentary'], correct: 0,
              explanation: '"Romantic comedy" combines a love story with humour.' },
            { id: 'u9-7',  type: 'vocabulary', topic: 'films',
              q: 'A film with aliens, spaceships, or future technology is ___.',
              options: ['fantasy', 'science fiction', 'thriller', 'documentary'], correct: 1,
              explanation: '"Science fiction" films use futuristic or scientific themes (aliens, robots, space).' },
            { id: 'u9-8',  type: 'vocabulary', topic: 'films',
              q: 'A suspenseful film with crime or danger that keeps you tense is a ___.',
              options: ['comedy', 'thriller', 'animation', 'documentary'], correct: 1,
              explanation: '"Thriller" films create excitement and suspense, often with crime or danger.' },
            { id: 'u9-9',  type: 'vocabulary', topic: 'see/watch',
              q: 'I went to ___ a film at the cinema last night.',
              options: ['watch', 'see', 'look', 'view'], correct: 1,
              explanation: 'For the EVENT of going to the cinema, we use "to see a film".' },
            { id: 'u9-10', type: 'vocabulary', topic: 'see/watch',
              q: 'I like ___ films with friends at home.',
              options: ['watching', 'seeing', 'looking', 'viewing'], correct: 0,
              explanation: 'For the ACTIVITY of viewing films (especially on TV/online), we use "watching".' },
            { id: 'u9-11', type: 'vocabulary', topic: 'films',
              q: 'In "Mother", a man is shot. The genre is "comedy ___".',
              options: ['romantic comedy', 'thriller', 'animation', 'horror'], correct: 1,
              explanation: 'A "comedy thriller" combines humour with suspense (like "Mother", described in the unit).' },
            { id: 'u9-12', type: 'vocabulary', topic: 'films',
              q: 'A film for the whole family with hand-drawn images is a(n) ___.',
              options: ['horror', 'thriller', 'animation', 'science fiction'], correct: 2,
              explanation: '"Animation" (e.g., "April and the Extraordinary World") is family-friendly cartoon-style film.' },

            // ════════ VOCABULARY: TV PROGRAMMES (8) ════════
            { id: 'u9-13', type: 'vocabulary', topic: 'TV',
              q: 'A TV programme about football, basketball, etc. is a ___.',
              options: ['drama series', 'sports programme', 'quiz show', 'horror film'], correct: 1,
              explanation: 'A "sports programme" shows or discusses sports.' },
            { id: 'u9-14', type: 'vocabulary', topic: 'TV',
              q: 'A TV show where contestants answer questions to win is a ___.',
              options: ['comedy show', 'drama series', 'quiz show', 'wildlife documentary'], correct: 2,
              explanation: 'A "quiz show" tests contestants\' knowledge with questions.' },
            { id: 'u9-15', type: 'vocabulary', topic: 'TV',
              q: 'A TV programme that informs you about events in the world is the ___.',
              options: ['quiz show', 'news', 'comedy', 'drama series'], correct: 1,
              explanation: '"The news" reports current events, weather, sports, and politics.' },
            { id: 'u9-16', type: 'vocabulary', topic: 'TV',
              q: 'A long story with episodes about characters\' lives is a ___.',
              options: ['quiz show', 'news', 'drama series', 'documentary'], correct: 2,
              explanation: 'A "drama series" tells a long story across many episodes.' },
            { id: 'u9-17', type: 'vocabulary', topic: 'TV',
              q: 'A documentary about lions, elephants, etc. is a ___.',
              options: ['news', 'comedy', 'wildlife documentary', 'quiz show'], correct: 2,
              explanation: 'A "wildlife documentary" focuses on animals in nature.' },
            { id: 'u9-18', type: 'vocabulary', topic: 'TV',
              q: 'Which adjective describes a TV show that makes you laugh?',
              options: ['scary', 'boring', 'funny', 'violent'], correct: 2,
              explanation: '"Funny" describes something that makes you laugh.' },
            { id: 'u9-19', type: 'vocabulary', topic: 'TV',
              q: 'A film with bloody fights might be described as ___.',
              options: ['exciting', 'violent', 'fun', 'boring'], correct: 1,
              explanation: '"Violent" means containing physical force or fighting.' },
            { id: 'u9-20', type: 'vocabulary', topic: 'TV',
              q: '"This is so ___! They are both playing really well." (about a sports game)',
              options: ['boring', 'scary', 'exciting', 'violent'], correct: 2,
              explanation: '"Exciting" describes a game/event that makes you feel excited and engaged.' },

            // ════════ VOCABULARY: NATURE (8) ════════
            { id: 'u9-21', type: 'vocabulary', topic: 'nature',
              q: 'Tall plants with leaves and branches that grow in forests are ___.',
              options: ['rocks', 'trees', 'flowers', 'lakes'], correct: 1,
              explanation: '"Trees" are tall plants. They grow in forests; their parts include leaves and branches.' },
            { id: 'u9-22', type: 'vocabulary', topic: 'nature',
              q: 'Large bodies of water surrounded by land are ___.',
              options: ['lakes', 'rocks', 'mountains', 'flowers'], correct: 0,
              explanation: '"Lakes" are large areas of water surrounded by land.' },
            { id: 'u9-23', type: 'vocabulary', topic: 'nature',
              q: 'Very high natural land formations are ___.',
              options: ['flowers', 'rocks', 'mountains', 'leaves'], correct: 2,
              explanation: '"Mountains" are very tall natural formations of rock and earth.' },
            { id: 'u9-24', type: 'vocabulary', topic: 'nature',
              q: 'Animals that fly with feathers are ___.',
              options: ['rocks', 'birds', 'trees', 'leaves'], correct: 1,
              explanation: '"Birds" have feathers, wings, and most can fly.' },
            { id: 'u9-25', type: 'vocabulary', topic: 'nature',
              q: 'The huge salty body of water around continents is the ___.',
              options: ['lake', 'sea', 'sky', 'rock'], correct: 1,
              explanation: 'The "sea" is a large body of salt water (smaller than an ocean).' },
            { id: 'u9-26', type: 'vocabulary', topic: 'nature',
              q: 'The blue or grey area above us is the ___.',
              options: ['sea', 'sky', 'tree', 'rock'], correct: 1,
              explanation: 'The "sky" is the air space above the earth, where clouds and the sun are seen.' },
            { id: 'u9-27', type: 'vocabulary', topic: 'nature',
              q: 'The green parts of a tree that fall in autumn are ___.',
              options: ['flowers', 'rocks', 'leaves', 'lakes'], correct: 2,
              explanation: '"Leaves" are the flat green parts of a tree (singular: leaf).' },
            { id: 'u9-28', type: 'vocabulary', topic: 'nature',
              q: 'Hard, solid pieces of stone are ___.',
              options: ['flowers', 'leaves', 'rocks', 'trees'], correct: 2,
              explanation: '"Rocks" are hard solid pieces of mineral material (smaller than mountains).' },

            // ════════ VOCABULARY: SENSE VERBS (5) ════════
            { id: 'u9-29', type: 'vocabulary', topic: 'sense verbs',
              q: 'This music ___ slow and disappointing.',
              options: ['looks', 'sounds', 'tastes', 'smells'], correct: 1,
              explanation: 'For describing what we HEAR (music), use "sounds + adjective".' },
            { id: 'u9-30', type: 'vocabulary', topic: 'sense verbs',
              q: 'These desserts ___ delicious.',
              options: ['look', 'feel', 'taste', 'sound'], correct: 2,
              explanation: 'For food, use "taste + adjective" (delicious, sweet, sour, salty).' },
            { id: 'u9-31', type: 'vocabulary', topic: 'sense verbs',
              q: 'This perfume ___ awful.',
              options: ['looks', 'sounds', 'tastes', 'smells'], correct: 3,
              explanation: 'For perfume / scents, use "smells + adjective".' },
            { id: 'u9-32', type: 'vocabulary', topic: 'sense verbs',
              q: 'Picasso\'s paintings ___ amazing!',
              options: ['look', 'sound', 'taste', 'smell'], correct: 0,
              explanation: 'For something visual (paintings), use "look + adjective".' },
            { id: 'u9-33', type: 'vocabulary', topic: 'sense verbs',
              q: 'The cotton fabric ___ soft.',
              options: ['feels', 'sounds', 'tastes', 'smells'], correct: 0,
              explanation: 'For touch / texture, use "feels + adjective" (soft, rough, smooth).' },

            // ════════ PRONUNCIATION (12) ════════
            { id: 'u9-34', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['cinema', 'gallery', 'museum', 'theatre'], correct: 2,
              explanation: '"Museum" /mjuˈziːəm/ stresses the SECOND syllable. The others stress the FIRST: CInema, GALlery, THEatre.' },
            { id: 'u9-35', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['fantasy', 'animation', 'documentary', 'comedy'], correct: 2,
              explanation: '"Documentary" /ˌdɒkjuˈmentəri/ stresses the THIRD syllable. The others stress the FIRST.' },
            { id: 'u9-36', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['horror', 'comedy', 'thriller', 'romantic'], correct: 3,
              explanation: '"Romantic" /rəʊˈmæntɪk/ stresses the SECOND syllable. The others stress the FIRST.' },
            { id: 'u9-37', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['exciting', 'interesting', 'amazing', 'fantastic'], correct: 1,
              explanation: '"INteresting" stresses the FIRST syllable. The others stress the SECOND: exCITing, aMAZing, fanTAStic.' },
            { id: 'u9-38', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['wildlife', 'wonderful', 'tomorrow', 'documentary (1st syll)'], correct: 2,
              explanation: '"Tomorrow" /təˈmɒrəʊ/ stresses the SECOND syllable. "Wildlife" and "wonderful" stress the FIRST.' },
            { id: 'u9-39', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['Sunday', 'today', 'morning', 'evening'], correct: 1,
              explanation: '"Today" /təˈdeɪ/ stresses the SECOND syllable. The others stress the FIRST.' },
            { id: 'u9-40', type: 'pronunciation', topic: '/tə/ in going to',
              q: 'In casual speech, "going to" is pronounced ___.',
              options: ['/ˈɡoʊ ɪŋ tuː/', '/ˈɡoʊɪŋ tə/ or "gonna"', '/ɡəʊ tuː/', '/ɡoʊ tuː ɔf/'], correct: 1,
              explanation: 'In fast/casual speech, "going to" is reduced to /ˈɡoʊɪŋ tə/ (and even further to "gonna" in informal English).' },
            { id: 'u9-41', type: 'pronunciation', topic: '/tə/ weak form',
              q: 'In "I want to go", the word "to" is usually pronounced ___.',
              options: ['/tuː/ (long)', '/tə/ (weak)', '/toʊ/', '/tʌ/'], correct: 1,
              explanation: 'When "to" is unstressed, it has a weak form /tə/ — a very short, neutral vowel sound.' },
            { id: 'u9-42', type: 'pronunciation', topic: 'showing enthusiasm',
              q: 'In "I\'d LOVE to!" which word is most stressed?',
              options: ['I\'d', 'love', 'to', 'all equally'], correct: 1,
              explanation: 'For enthusiasm, stress the emotional word — "LOVE". This shows you really mean it.' },
            { id: 'u9-43', type: 'pronunciation', topic: 'showing enthusiasm',
              q: 'In "That sounds FANTASTIC!" which word is most stressed?',
              options: ['that', 'sounds', 'fantastic', 'all the same'], correct: 2,
              explanation: 'The emotional/descriptive word "FANTASTIC" gets the strongest stress to express enthusiasm.' },
            { id: 'u9-44', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['cinema', 'cinemas', 'concert', 'computer'], correct: 3,
              explanation: '"Computer" /kəmˈpjuːtər/ stresses the SECOND syllable. The others stress the FIRST: CInema, CInemas, CONcert.' },
            { id: 'u9-45', type: 'pronunciation', topic: 'word stress',
              q: 'Choose the word with stress on a DIFFERENT syllable.',
              options: ['picture', 'painting', 'design', 'sculpture'], correct: 2,
              explanation: '"Design" /dɪˈzaɪn/ stresses the SECOND syllable. The others stress the FIRST.' },

            // ════════ GRAMMAR: BE GOING TO (20) ════════
            { id: 'u9-46', type: 'grammar', topic: 'be going to',
              q: 'I ___ buy a ticket for the next film.',
              options: ['going to', 'am going to', 'is going to', 'be going to'], correct: 1,
              explanation: 'For plans, use "am/is/are + going to + base verb". With "I" → "am going to".' },
            { id: 'u9-47', type: 'grammar', topic: 'be going to',
              q: 'They ___ stay out late tonight.',
              options: ['aren\'t going to', 'don\'t going to', 'isn\'t going to', 'not going to'], correct: 0,
              explanation: 'Negative: subject + am/is/are + NOT + going to + verb. With "they" → "aren\'t going to".' },
            { id: 'u9-48', type: 'grammar', topic: 'be going to',
              q: 'What ___ you ___ do this weekend?',
              options: ['do / going to', 'are / going to', 'are / go to', 'do / go to'], correct: 1,
              explanation: 'Question: Wh-word + am/is/are + subject + going to + verb? "What are you going to do?"' },
            { id: 'u9-49', type: 'grammar', topic: 'be going to',
              q: '"Are you going to see the film?" "Yes, ___."',
              options: ['I am', 'I do', 'I going to', 'I will'], correct: 0,
              explanation: 'Short answer: "Yes, I am / No, I\'m not".' },
            { id: 'u9-50', type: 'grammar', topic: 'be going to',
              q: 'In standard English, we don\'t usually say "I\'m going to GO to work tomorrow." We just say:',
              options: ['I\'m going to work tomorrow.', 'I am to work tomorrow.', 'I work to tomorrow.', 'I\'m gonna to work tomorrow.'], correct: 0,
              explanation: 'When the main verb after "going to" is "go", we drop it: "I\'m going TO work" (not "going to GO to work").' },
            { id: 'u9-51', type: 'grammar', topic: 'be going to',
              q: 'We ___ a film at the new cinema.',
              options: ['going to see', 'are going to see', 'is going see', 'go to seeing'], correct: 1,
              explanation: '"We" + "are going to" + base verb → "are going to see".' },
            { id: 'u9-52', type: 'grammar', topic: 'be going to',
              q: 'I ___ a ticket. It\'s too expensive.',
              options: ['not buy', 'am not going to buy', 'don\'t going to buy', 'isn\'t going to buy'], correct: 1,
              explanation: 'Negative plan with "I" → "am not going to" + base verb.' },
            { id: 'u9-53', type: 'grammar', topic: 'be going to',
              q: '___ you ___ the tickets online or at the cinema?',
              options: ['Do / buy', 'Are / buying', 'Are / going to buy', 'Will / going to'], correct: 2,
              explanation: 'Future plan question: "Are you going to buy" + the tickets.' },
            { id: 'u9-54', type: 'grammar', topic: 'be going to',
              q: 'Where ___ you ___ sit?',
              options: ['are / going to', 'do / going to', 'are / go to', 'will / going'], correct: 0,
              explanation: 'Wh-question: "Where are you going to sit?" — present continuous of "be" + going to + base verb.' },
            { id: 'u9-55', type: 'grammar', topic: 'be going to',
              q: 'I ___ the film. It starts at midnight.',
              options: ['am not going to watch', 'don\'t going to watch', 'going to not watch', 'am not watching to'], correct: 0,
              explanation: 'Negative plan: "I am not going to watch" (the film, because it\'s too late).' },
            { id: 'u9-56', type: 'grammar', topic: 'be going to',
              q: 'Where ___ you ___ go after the film?',
              options: ['do / going', 'are / going to', 'is / going to', 'are / go to'], correct: 1,
              explanation: '"Where are you going to go..." — the question form of "be going to".' },
            { id: 'u9-57', type: 'grammar', topic: 'be going to',
              q: 'They ___ us in the centre of town.',
              options: ['going to meet', 'are going to meet', 'is going to meet', 'goes to meet'], correct: 1,
              explanation: 'Plural subject "they" → "are going to" + base verb.' },
            { id: 'u9-58', type: 'grammar', topic: 'be going to',
              q: 'I ___ a film by that director again!',
              options: ['am never going to watch', 'never going to watch', 'don\'t never going to', 'am never going watch'], correct: 0,
              explanation: '"Never" goes between "am/is/are" and "going to" → "I am never going to watch".' },
            { id: 'u9-59', type: 'grammar', topic: 'be going to',
              q: 'We ___ a film on TV this evening.',
              options: ['are going to watch', 'going watch', 'are going watch', 'is going to watch'], correct: 0,
              explanation: 'Plural "we" → "are going to" + watch (base form).' },
            { id: 'u9-60', type: 'grammar', topic: 'be going to',
              q: 'Matt and Raul ___ tennis tomorrow.',
              options: ['going play', 'are going to play', 'is going to play', 'go to play'], correct: 1,
              explanation: 'Plural subject → "are going to" + base verb.' },
            { id: 'u9-61', type: 'grammar', topic: 'be going to',
              q: 'I ___ friends for dinner tonight.',
              options: ['going to have', 'am going to have', 'am going have', 'have going to'], correct: 1,
              explanation: '"I am going to have friends..." — first person singular plan.' },
            { id: 'u9-62', type: 'grammar', topic: 'be going to',
              q: 'They ___ here because there\'s a problem with their car.',
              options: ['aren\'t going to come', 'not going come', 'don\'t going to come', 'isn\'t going come'], correct: 0,
              explanation: 'Negative plan with "they" → "aren\'t going to come".' },
            { id: 'u9-63', type: 'grammar', topic: 'be going to',
              q: '___ you ___ a holiday this year?',
              options: ['Do / having', 'Are / going to have', 'Is / having', 'Will / have'], correct: 1,
              explanation: 'Question: "Are you going to have a holiday?" — plan-related, so use "be going to".' },
            { id: 'u9-64', type: 'grammar', topic: 'be going to',
              q: 'Rachel ___ the tickets online before we leave.',
              options: ['is going to buy', 'going to buy', 'are going to buy', 'go to buy'], correct: 0,
              explanation: 'Singular "Rachel" → "is going to" + base verb.' },
            { id: 'u9-65', type: 'grammar', topic: 'be going to',
              q: 'The author ___ another book ever again.',
              options: ['isn\'t going to write', 'going not write', 'don\'t going write', 'aren\'t going write'], correct: 0,
              explanation: 'Singular subject "the author" → "isn\'t going to write".' },

            // ════════ GRAMMAR: INFINITIVE OF PURPOSE (10) ════════
            { id: 'u9-66', type: 'grammar', topic: 'infinitive of purpose',
              q: 'Turn on the TV ___ the news.',
              options: ['for watch', 'to watch', 'for watching', 'watch'], correct: 1,
              explanation: 'To express purpose ("why we do something"), use "to + base verb". "Turn on the TV TO WATCH the news".' },
            { id: 'u9-67', type: 'grammar', topic: 'infinitive of purpose',
              q: 'Go online ___ a "How to" video.',
              options: ['for find', 'finding', 'to find', 'for to find'], correct: 2,
              explanation: 'Purpose → "to + base verb": "Go online TO FIND a video".' },
            { id: 'u9-68', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I\'m going to record this film ___ later.',
              options: ['watching', 'for watching', 'to watch', 'for to watch'], correct: 2,
              explanation: '"To watch it later" — gives the reason (the purpose) for recording the film.' },
            { id: 'u9-69', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I\'m going to read this book about Martin Scorsese ___ his life.',
              options: ['to find out about', 'for finding out about', 'finding out about', 'for to find out'], correct: 0,
              explanation: 'Purpose: "to find out about" — read the book in order to learn about his life.' },
            { id: 'u9-70', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I\'m going to art school ___ painting.',
              options: ['for studying', 'study', 'studying', 'to study'], correct: 3,
              explanation: 'Purpose / reason for going → "to + base verb": "TO STUDY".' },
            { id: 'u9-71', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I play this computer game again ___ level five.',
              options: ['for reach', 'to reach', 'reach', 'for reaching'], correct: 1,
              explanation: '"to reach level five" tells WHY I\'m playing again.' },
            { id: 'u9-72', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I\'m going to buy theatre tickets ___ a play by Shakespeare.',
              options: ['to see', 'seeing', 'for see', 'for seeing'], correct: 0,
              explanation: 'Purpose → "to see". Buy tickets WHY? "to see a play".' },
            { id: 'u9-73', type: 'grammar', topic: 'infinitive of purpose',
              q: 'I want to watch these videos ___ how to play the guitar.',
              options: ['for learn', 'learning', 'to learn', 'for to learn'], correct: 2,
              explanation: 'Purpose: "to learn how to play". Use "to + base verb".' },
            { id: 'u9-74', type: 'grammar', topic: 'infinitive of purpose',
              q: 'He went to Honduras ___ a film about the rainforest.',
              options: ['making', 'to make', 'for make', 'for making'], correct: 1,
              explanation: 'Purpose: "to make a film". The infinitive of purpose tells WHY he went.' },
            { id: 'u9-75', type: 'grammar', topic: 'infinitive of purpose',
              q: 'In winter, he\'s going to Indonesia ___ a holiday.',
              options: ['for have', 'to have', 'for to have', 'having'], correct: 1,
              explanation: 'Purpose: "to have a holiday" — the reason for going to Indonesia.' },

            // ════════ REAL LIFE: INVITING & ARRANGEMENTS (10) ════════
            { id: 'u9-76', type: 'grammar', topic: 'inviting',
              q: 'Which is correct for an invitation?',
              options: ['Would you like to come?', 'Would you like come?', 'Do you like to come?', 'You like come?'], correct: 0,
              explanation: '"Would you like + to + verb?" is the standard invitation pattern.' },
            { id: 'u9-77', type: 'grammar', topic: 'inviting',
              q: '"Are you ___ tonight?" "Yes, I am."',
              options: ['free', 'going', 'will', 'come'], correct: 0,
              explanation: '"Are you free tonight?" is a common way to ask about availability before inviting.' },
            { id: 'u9-78', type: 'grammar', topic: 'inviting',
              q: 'Which is a polite way to invite someone?',
              options: ['You come!', 'Do you want to go?', 'You go.', 'Come!'], correct: 1,
              explanation: '"Do you want to go...?" is friendly. The other options are too direct/commanding.' },
            { id: 'u9-79', type: 'grammar', topic: 'responding to invitations',
              q: 'Which response ACCEPTS an invitation enthusiastically?',
              options: ['I\'d love to!', 'I can\'t.', 'Maybe.', 'I\'m sorry.'], correct: 0,
              explanation: '"I\'d love to!" is an enthusiastic YES.' },
            { id: 'u9-80', type: 'grammar', topic: 'responding to invitations',
              q: 'Which response politely DECLINES an invitation?',
              options: ['Yes, please.', 'I\'m sorry, but I\'m working late tonight.', 'I\'d love to.', 'That sounds fantastic.'], correct: 1,
              explanation: 'Politely declining: "I\'m sorry, but..." + a reason (e.g., "I\'m working late").' },
            { id: 'u9-81', type: 'grammar', topic: 'arrangements',
              q: '"What time ___ it start?"',
              options: ['do', 'does', 'is', 'are'], correct: 1,
              explanation: '"It" is third-person singular → use "DOES it start?" in present simple questions.' },
            { id: 'u9-82', type: 'grammar', topic: 'arrangements',
              q: '"___ meet at seven."',
              options: ['Let\'s', 'Let us to', 'Let we', 'We let'], correct: 0,
              explanation: '"Let\'s" (= let us) is the standard suggestion form: "Let\'s + base verb".' },
            { id: 'u9-83', type: 'grammar', topic: 'arrangements',
              q: '"___ you at seven." (= "I will see you at seven")',
              options: ['Sees', 'See', 'I see', 'See you'], correct: 3,
              explanation: '"See you at seven" is the friendly informal way to confirm a meeting time.' },
            { id: 'u9-84', type: 'grammar', topic: 'inviting',
              q: 'Complete: "Do you ___ to come?"',
              options: ['like', 'want', 'go', 'see'], correct: 1,
              explanation: '"Do you WANT to come?" is informal and direct. ("Would you LIKE to come?" is more polite.)' },
            { id: 'u9-85', type: 'grammar', topic: 'responding to invitations',
              q: 'Which is the most positive enthusiastic reply?',
              options: ['That\'s OK.', 'That\'s fine.', 'That\'s great!', 'That\'s alright.'], correct: 2,
              explanation: '"That\'s great!" expresses enthusiasm. The others are neutral.' },

            // ════════ READING / CRITICAL THINKING (10) ════════
            { id: 'u9-86', type: 'vocabulary', topic: 'films',
              q: 'According to the unit, the Tallgrass Film Festival shows films from ___ countries.',
              options: ['10', '20', '33', '100'], correct: 2,
              explanation: 'The article says the festival shows more than 190 films from 33 different countries.' },
            { id: 'u9-87', type: 'vocabulary', topic: 'films',
              q: 'In the article, "April and the Extraordinary World" is in ___ with English subtitles.',
              options: ['Spanish', 'French', 'Japanese', 'German'], correct: 1,
              explanation: 'The article describes it as "In French with English subtitles".' },
            { id: 'u9-88', type: 'vocabulary', topic: 'films',
              q: 'In the unit, the film "Brother" is set in ___.',
              options: ['Estonia', 'France', 'Venezuela', 'Honduras'], correct: 2,
              explanation: '"In a drama from Venezuela, two brothers grow up in Caracas..." (Caracas is in Venezuela.)' },
            { id: 'u9-89', type: 'vocabulary', topic: 'art',
              q: 'Vincent van Gogh made ___ paintings of sunflowers.',
              options: ['five', 'eleven', 'twenty', 'fifty'], correct: 1,
              explanation: 'The article says "Vincent van Gogh made eleven paintings of sunflowers".' },
            { id: 'u9-90', type: 'vocabulary', topic: 'art',
              q: 'Andō Hiroshige worked in the ___ century.',
              options: ['16th', '18th', '19th', '20th'], correct: 2,
              explanation: 'The article says "Andō Hiroshige worked in the nineteenth century".' },
            { id: 'u9-91', type: 'vocabulary', topic: 'art',
              q: 'Beatriz Milhazes is a ___ artist.',
              options: ['Polish', 'Japanese', 'Brazilian', 'Dutch'], correct: 2,
              explanation: '"Beatriz Milhazes is a Brazilian artist from Rio de Janeiro."' },
            { id: 'u9-92', type: 'vocabulary', topic: 'films',
              q: '"This comedy thriller is BY the director Kadri Kõusaar." Here "by" indicates ___.',
              options: ['near', 'before', 'made by (creator)', 'at'], correct: 2,
              explanation: 'When talking about creative works (films, books), "by" tells us WHO MADE it.' },
            { id: 'u9-93', type: 'vocabulary', topic: 'wildlife',
              q: 'A "camera trap" is a device that ___.',
              options: ['traps animals', 'takes photos when an animal moves in front of it', 'records sounds only', 'measures temperature'], correct: 1,
              explanation: 'A camera trap automatically takes photos when motion is detected.' },
            { id: 'u9-94', type: 'vocabulary', topic: 'wildlife',
              q: 'A "rainforest" is ___.',
              options: ['a desert', 'a place with many trees and different types of wildlife', 'a city park', 'an empty field'], correct: 1,
              explanation: 'A rainforest has many trees and supports rich wildlife — common in Central/South America.' },
            { id: 'u9-95', type: 'vocabulary', topic: 'wildlife',
              q: 'A "species" is ___.',
              options: ['a single animal', 'a type or group of animals', 'a hunting tool', 'a forest'], correct: 1,
              explanation: '"Species" = a type/group of animals (or plants), e.g., lions and tigers are different species.' },

            // ════════ WRITING / REVIEWS (5) ════════
            { id: 'u9-96', type: 'vocabulary', topic: 'reviews',
              q: 'A review that PRAISES something is ___.',
              options: ['negative', 'positive', 'angry', 'tired'], correct: 1,
              explanation: 'A "positive" review says good things. A "negative" review criticises.' },
            { id: 'u9-97', type: 'vocabulary', topic: 'reviews',
              q: '"The food tasted ___ — we waited an hour and it was cold."',
              options: ['delicious', 'amazing', 'terrible', 'wonderful'], correct: 2,
              explanation: 'This describes a NEGATIVE experience (cold, long wait) → "terrible" matches.' },
            { id: 'u9-98', type: 'vocabulary', topic: 'reviews',
              q: 'Which adjective could describe music played quietly?',
              options: ['loud', 'soft', 'angry', 'bored'], correct: 1,
              explanation: '"Soft" music is quiet/gentle. "Loud" is the opposite.' },
            { id: 'u9-99', type: 'vocabulary', topic: 'reviews',
              q: 'A "delicious" cake ___.',
              options: ['looks bad', 'tastes terrible', 'tastes wonderful', 'is small'], correct: 2,
              explanation: '"Delicious" = tastes very good. Used especially for food.' },
            { id: 'u9-100', type: 'vocabulary', topic: 'reviews',
              q: 'A perfume that "smells awful" is ___.',
              options: ['nice', 'positive', 'pleasant', 'not nice'], correct: 3,
              explanation: '"Awful" = very bad / not nice. Awful smells / awful weather / awful film all mean very bad.' },

            // ════════ PRONUNCIATION: UNDERLINED LETTER (20) ════════
            // Format: "Choose the word that has the underlined part pronounced differently from the others"
            { id: 'u9-101', type: 'pronunciation', topic: 'underlined letter (c: /k/ vs /s/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['<u>c</u>inema', '<u>c</u>omedy', '<u>c</u>oncert', '<u>c</u>amera'], correct: 0,
              explanation: 'In "cinema" /ˈsɪnəmə/ the <u>c</u> sounds /s/ (because of the "i" after it). In "comedy, concert, camera" the <u>c</u> sounds /k/. Rule: "c" before e/i/y is /s/; before a/o/u or a consonant it is /k/.' },
            { id: 'u9-102', type: 'pronunciation', topic: 'underlined letter (ea: /iː/ vs /e/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['s<u>ea</u>', 'l<u>ea</u>ves', 'r<u>ea</u>l', 'h<u>ea</u>d'], correct: 3,
              explanation: '"head" /hed/ has the short /e/ sound. "Sea, leaves, real" all use the long /iː/ sound.' },
            { id: 'u9-103', type: 'pronunciation', topic: 'underlined letter (ee: /iː/ vs /ɪ/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['s<u>ee</u>', 'thr<u>ee</u>', 'b<u>ee</u>n', 'tr<u>ee</u>'], correct: 2,
              explanation: '"been" /bɪn/ in many British accents is short /ɪ/. "See, three, tree" all use the long /iː/. (In American English, "been" can also be /biːn/ — the test is the British pronunciation here.)' },
            { id: 'u9-104', type: 'pronunciation', topic: 'underlined letter (g: /g/ vs /dʒ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['<u>g</u>allery', '<u>g</u>oing', 'lar<u>g</u>e', '<u>g</u>rass'], correct: 2,
              explanation: 'In "large" /lɑːdʒ/ the <u>g</u> is /dʒ/ (because of the "e" after it). "Gallery, going, grass" all have /g/.' },
            { id: 'u9-105', type: 'pronunciation', topic: 'underlined letter (ch: /tʃ/ vs /k/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>ch</u>oose', '<u>ch</u>eap', 'or<u>ch</u>estra', '<u>ch</u>icken'], correct: 2,
              explanation: 'In "orchestra" /ˈɔːkɪstrə/ the <u>ch</u> sounds /k/. In "choose, cheap, chicken" it is /tʃ/.' },
            { id: 'u9-106', type: 'pronunciation', topic: 'underlined letter (a: /eɪ/ vs /æ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['pl<u>a</u>y', 'r<u>a</u>in', 'pl<u>a</u>n', 'm<u>a</u>ke'], correct: 2,
              explanation: '"plan" /plæn/ has the short /æ/ sound. "Play, rain, make" all have the long /eɪ/ sound (ay-sound).' },
            { id: 'u9-107', type: 'pronunciation', topic: 'underlined letter (final s: /s/ vs /z/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['film<u>s</u>', 'play<u>s</u>', 'lake<u>s</u>', 'tree<u>s</u>'], correct: 2,
              explanation: '"lakes" /leɪks/ ends with /s/ (after voiceless /k/). "Films, plays, trees" all end with /z/ (after voiced sounds).' },
            { id: 'u9-108', type: 'pronunciation', topic: 'underlined letter (ou: /aʊ/ vs /uː/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['s<u>ou</u>nd', 'l<u>ou</u>d', 'gr<u>ou</u>p', 'cl<u>ou</u>d'], correct: 2,
              explanation: '"group" /ɡruːp/ uses /uː/. "Sound, loud, cloud" all use /aʊ/ (the "now"-sound).' },
            { id: 'u9-109', type: 'pronunciation', topic: 'underlined letter (oo: /uː/ vs /ʊ/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['l<u>oo</u>k', 'g<u>oo</u>d', 'b<u>oo</u>k', 'fo<u>o</u>d'], correct: 3,
              explanation: '"food" /fuːd/ has the long /uː/. "Look, good, book" all have the short /ʊ/.' },
            { id: 'u9-110', type: 'pronunciation', topic: 'underlined letter (i: /aɪ/ vs /ɪ/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['l<u>i</u>fe', 'l<u>i</u>ke', 'l<u>i</u>ttle', 'wh<u>i</u>te'], correct: 2,
              explanation: '"little" /ˈlɪtl/ uses the short /ɪ/. "Life, like, white" all use the diphthong /aɪ/.' },
            { id: 'u9-111', type: 'pronunciation', topic: 'underlined letter (th: /θ/ vs /ð/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>th</u>eatre', '<u>th</u>ank', '<u>th</u>e', '<u>th</u>ree'], correct: 2,
              explanation: '"the" /ðə/ uses voiced /ð/. "Theatre, thank, three" all use unvoiced /θ/.' },
            { id: 'u9-112', type: 'pronunciation', topic: 'underlined letter (or: /ɔː/ vs /ɜː/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['sp<u>or</u>t', 'sh<u>or</u>t', 'w<u>or</u>d', 'm<u>or</u>e'], correct: 2,
              explanation: '"word" /wɜːd/ uses /ɜː/ (her-vowel). "Sport, short, more" all use /ɔː/ (door-vowel).' },
            { id: 'u9-113', type: 'pronunciation', topic: 'underlined letter (silent k)',
              q: 'In which word is the underlined letter SILENT?',
              options: ['<u>k</u>iss', '<u>k</u>now', '<u>k</u>ettle', '<u>k</u>ind'], correct: 1,
              explanation: 'In "know" /nəʊ/ the <u>k</u> is silent. Same for "knee, knife, knock". Only when "k" appears before "n" at the start of a word.' },
            { id: 'u9-114', type: 'pronunciation', topic: 'underlined letter (ow: /aʊ/ vs /əʊ/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['kn<u>ow</u>', 'sh<u>ow</u>', 'h<u>ow</u>', 'sl<u>ow</u>'], correct: 2,
              explanation: '"how" /haʊ/ uses /aʊ/. "Know, show, slow" all use /əʊ/ (like "go"). The spelling "ow" can sound either way depending on the word.' },
            { id: 'u9-115', type: 'pronunciation', topic: 'underlined letter (a: /æ/ vs /ɔː/)',
              q: 'Choose the word that has the underlined letter pronounced differently from the others.',
              options: ['anim<u>a</u>tion', 'f<u>a</u>ntasy', 'h<u>a</u>ppy', 'w<u>a</u>tch'], correct: 3,
              explanation: '"watch" /wɒtʃ/ (BrE) or /wɑːtʃ/ (AmE) uses /ɒ/ or /ɑː/ (different from /æ/). "Animation, fantasy, happy" all have /æ/ (the cat-vowel).' },
            { id: 'u9-116', type: 'pronunciation', topic: 'underlined letter (ar: /ɑː/ vs /ɔː/)',
              q: 'Choose the word that has the underlined part pronounced differently from the others.',
              options: ['<u>ar</u>t', 'p<u>ar</u>k', 'st<u>ar</u>t', 'w<u>ar</u>'], correct: 3,
              explanation: '"war" /wɔː/ uses /ɔː/. "Art, park, start" all use /ɑː/ (the long-a sound).' },
            { id: 'u9-117', type: 'pronunciation', topic: 'underlined letter (final ed: /t/ vs /d/ vs /ɪd/)',
              q: 'Choose the word that has the underlined ending pronounced differently from the others.',
              options: ['watch<u>ed</u>', 'film<u>ed</u>', 'play<u>ed</u>', 'enjoy<u>ed</u>'], correct: 0,
              explanation: '"watched" /wɒtʃt/ ends with /t/ (after the voiceless /tʃ/). "Filmed, played, enjoyed" all end with /d/ (after voiced sounds).' },
            { id: 'u9-118', type: 'pronunciation', topic: 'underlined letter (final ed: /t/ vs /d/ vs /ɪd/)',
              q: 'Choose the word that has the underlined ending pronounced differently from the others.',
              options: ['paint<u>ed</u>', 'lik<u>ed</u>', 'walk<u>ed</u>', 'help<u>ed</u>'], correct: 0,
              explanation: '"painted" /ˈpeɪntɪd/ ends with /ɪd/ (after /t/ or /d/, "-ed" becomes a separate syllable). "Liked, walked, helped" all end with just /t/.' },
            { id: 'u9-119', type: 'pronunciation', topic: 'underlined letter (silent w)',
              q: 'In which word is the underlined letter SILENT?',
              options: ['<u>w</u>atch', '<u>w</u>ar', '<u>w</u>rite', '<u>w</u>onderful'], correct: 2,
              explanation: 'In "write" /raɪt/ the <u>w</u> is silent. Also silent in "wrong, wrap, wrist" — when "w" appears before "r" at the start of a word.' },
            { id: 'u9-120', type: 'pronunciation', topic: 'underlined letter (final s: /s/ vs /z/ vs /ɪz/)',
              q: 'Choose the word that has the underlined ending pronounced differently from the others.',
              options: ['rock<u>s</u>', 'mountain<u>s</u>', 'leaf -> leave<u>s</u>', 'bird<u>s</u>'], correct: 0,
              explanation: '"rocks" /rɒks/ ends with /s/ (after voiceless /k/). "Mountains, leaves, birds" all end with /z/ (after voiced sounds).' }
        ]
    }
];

// ==================== HELPERS ====================

// Get the unit by id
function getGrammarUnit(unitId) {
    return GRAMMAR_UNITS.find(u => u.id === unitId);
}

// Generate a quiz of N random questions from a unit
function generateGrammarQuiz(unitId, n) {
    const unit = getGrammarUnit(unitId);
    if (!unit) return [];
    const pool = [...unit.questions];
    // Fisher-Yates shuffle
    for (let i = pool.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    return pool.slice(0, Math.min(n, pool.length));
}

// Stats per unit (best score, attempts, last attempt)
function getGrammarStats(unitId) {
    if (!appState || !appState.grammarHistory) return { attempts: 0, best: null, last: null };
    const sessions = appState.grammarHistory.filter(s => s.unitId === unitId);
    if (sessions.length === 0) return { attempts: 0, best: null, last: null };
    const sorted = [...sessions].sort((a, b) => b.date - a.date);
    const best = sessions.reduce((acc, s) => (!acc || s.score > acc.score) ? s : acc, null);
    return { attempts: sessions.length, best, last: sorted[0] };
}

// Save a completed quiz session to history
function saveGrammarSession(unitId, questions, answers) {
    if (!appState) return;
    if (!appState.grammarHistory) appState.grammarHistory = [];
    const correctCount = questions.reduce((sum, q, i) => sum + (answers[i] === q.correct ? 1 : 0), 0);
    const session = {
        id: 'g-' + Date.now(),
        unitId,
        date: Date.now(),
        score: correctCount,
        total: questions.length,
        questions: questions.map((q, i) => ({
            id: q.id,
            type: q.type,
            topic: q.topic,
            q: q.q,
            options: q.options,
            correct: q.correct,
            explanation: q.explanation,
            userAnswer: answers[i]
        }))
    };
    appState.grammarHistory.unshift(session); // Newest first
    // Cap history at 50 sessions
    if (appState.grammarHistory.length > 50) appState.grammarHistory = appState.grammarHistory.slice(0, 50);
    saveUserData(currentUser, appState);
    return session;
}
