// hot-words.js — GENERATED by scripts/build-hot-words.js. Do not edit.
// The 100 commonest words across every quiz bank: 48% of all
// tappable text, 1.3 MB of audio. js/app.js warms these in the
// background so most tap-to-hear taps never wait on the network.
const HOT_WORDS = ["the","a","to","of","and","in","so","company","is","our","for","new","it","with","on","that","every","about","can","news","good","people","was","an","from","its","we","team","public","her","at","customers","before","media","one","reporters","after","will","because","campaign","pr","relations","she","their","story","not","publicist","as","he","manager","product","many","them","what","press","small","they","factory","out","when","who","you","had","has","local","must","only","short","your","are","by","could","job","more","client","company's","day","how","meeting","next","release","sent","social","year","city","information","instead","photos","plan","radio","some","up","work","all","angry","answer","business","customer","his","message"];

if (typeof module !== 'undefined' && module.exports) { module.exports = { HOT_WORDS }; }
