// hot-words.js — GENERATED by scripts/build-hot-words.js. Do not edit.
// The 100 commonest words across every quiz bank: 43% of all
// tappable text, 1.3 MB of audio. js/app.js warms these in the
// background so most tap-to-hear taps never wait on the network.
const HOT_WORDS = ["the","to","a","in","of","is","and","for","at","are","has","on","i","have","you","with","that","was","my","from","it","will","they","can","their","this","many","we","which","she","every","so","new","our","not","her","about","as","your","when","by","people","more","were","or","before","last","he","going","an","do","after","had","school","word","his","students","but","time","how","one","them","because","make","year","than","up","years","all","no","now","who","day","first","small","work","often","most","two","old","others","what","there","food","long","also","part","use","true","over","like","false","morning","next","don't","be","even","young","water","out"];

if (typeof module !== 'undefined' && module.exports) { module.exports = { HOT_WORDS }; }
