// hot-words.js — GENERATED by scripts/build-hot-words.js. Do not edit.
// The 100 commonest words across every quiz bank: 48% of all
// tappable text, 1.4 MB of audio. js/app.js warms these in the
// background so most tap-to-hear taps never wait on the network.
const HOT_WORDS = ["the","a","to","of","and","so","in","company","it","our","for","is","new","on","with","every","that","people","news","about","was","we","its","after","can","an","before","from","team","campaign","good","one","media","her","at","because","public","she","as","reporters","their","will","customers","story","pr","product","not","publicist","press","relations","he","only","out","by","day","manager","many","them","up","what","had","they","could","instead","some","when","are","asked","factory","has","release","social","tv","information","message","sent","short","two","company's","more","online","own","question","small","talk","who","whole","you","agency","all","best","customer","group","how","must","newspaper","next","photos","questions","sales"];

if (typeof module !== 'undefined' && module.exports) { module.exports = { HOT_WORDS }; }
