// units-data.js — Picture-dictionary word bank for the Topics tab "Unit 1..12"
// chips (extracted from the student's textbook picture dictionary).
// Schema: { unit, en, vi, emoji } — emoji is the "picture" (digits for numbers,
// symbol pairs for direction words, matching the book's own icons).
const UNIT_WORDS = [
  // ── Unit 1: Jobs & places ──
  { unit: 1, en: 'doctor', vi: 'bác sĩ', emoji: '👩‍⚕️' },
  { unit: 1, en: 'pilot', vi: 'phi công', emoji: '👨‍✈️' },
  { unit: 1, en: 'firefighter', vi: 'lính cứu hỏa', emoji: '👨‍🚒' },
  { unit: 1, en: 'student', vi: 'học sinh', emoji: '🧑‍🎓' },
  { unit: 1, en: 'teacher', vi: 'giáo viên', emoji: '👩‍🏫' },
  { unit: 1, en: 'police officer', vi: 'cảnh sát', emoji: '👮' },
  { unit: 1, en: 'farmer', vi: 'nông dân', emoji: '👨‍🌾' },
  { unit: 1, en: 'fire station', vi: 'trạm cứu hỏa', emoji: '🚒' },
  { unit: 1, en: 'store', vi: 'cửa hàng', emoji: '🏪' },
  { unit: 1, en: 'office', vi: 'văn phòng', emoji: '🏢' },
  { unit: 1, en: 'farm', vi: 'nông trại', emoji: '🐄' },
  { unit: 1, en: 'bank', vi: 'ngân hàng', emoji: '🏦' },

  // ── Unit 2: Places & animals ──
  { unit: 2, en: 'hospital', vi: 'bệnh viện', emoji: '🏥' },
  { unit: 2, en: 'airport', vi: 'sân bay', emoji: '✈️' },
  { unit: 2, en: 'police station', vi: 'đồn cảnh sát', emoji: '🚓' },
  { unit: 2, en: 'nest', vi: 'tổ chim', emoji: '🪺' },
  { unit: 2, en: 'octopus', vi: 'bạch tuộc', emoji: '🐙' },
  { unit: 2, en: 'parrot', vi: 'con vẹt', emoji: '🦜' },

  // ── Unit 3: Food & numbers ──
  { unit: 3, en: 'bubble tea', vi: 'trà sữa trân châu', emoji: '🧋' },
  { unit: 3, en: 'chicken', vi: 'thịt gà', emoji: '🍗' },
  { unit: 3, en: 'fries', vi: 'khoai tây chiên', emoji: '🍟' },
  { unit: 3, en: 'noodles', vi: 'mì', emoji: '🍜' },
  { unit: 3, en: 'pizza', vi: 'bánh pizza', emoji: '🍕' },
  { unit: 3, en: 'ten', vi: 'mười', emoji: '10' },
  { unit: 3, en: 'twenty', vi: 'hai mươi', emoji: '20' },
  { unit: 3, en: 'twenty-one', vi: 'hai mươi mốt', emoji: '21' },
  { unit: 3, en: 'twenty-two', vi: 'hai mươi hai', emoji: '22' },
  { unit: 3, en: 'twenty-three', vi: 'hai mươi ba', emoji: '23' },
  { unit: 3, en: 'twenty-four', vi: 'hai mươi bốn', emoji: '24' },
  { unit: 3, en: 'twenty-five', vi: 'hai mươi lăm', emoji: '25' },
  { unit: 3, en: 'twenty-six', vi: 'hai mươi sáu', emoji: '26' },
  { unit: 3, en: 'twenty-seven', vi: 'hai mươi bảy', emoji: '27' },
  { unit: 3, en: 'twenty-eight', vi: 'hai mươi tám', emoji: '28' },
  { unit: 3, en: 'twenty-nine', vi: 'hai mươi chín', emoji: '29' },
  { unit: 3, en: 'thirty', vi: 'ba mươi', emoji: '30' },
  { unit: 3, en: 'forty', vi: 'bốn mươi', emoji: '40' },
  { unit: 3, en: 'fifty', vi: 'năm mươi', emoji: '50' },
  { unit: 3, en: 'sixty', vi: 'sáu mươi', emoji: '60' },
  { unit: 3, en: 'seventy', vi: 'bảy mươi', emoji: '70' },
  { unit: 3, en: 'eighty', vi: 'tám mươi', emoji: '80' },
  { unit: 3, en: 'ninety', vi: 'chín mươi', emoji: '90' },
  { unit: 3, en: 'one hundred', vi: 'một trăm', emoji: '100' },
  { unit: 3, en: 'queen', vi: 'nữ hoàng', emoji: '👑' },
  { unit: 3, en: 'rabbit', vi: 'con thỏ', emoji: '🐰' },
  { unit: 3, en: 'sofa', vi: 'ghế sofa', emoji: '🛋️' },

  // ── Unit 4: School subjects & rooms ──
  { unit: 4, en: 'art', vi: 'mĩ thuật', emoji: '🎨' },
  { unit: 4, en: 'math', vi: 'môn toán', emoji: '➗' },
  { unit: 4, en: 'English', vi: 'tiếng Anh', emoji: '🇬🇧' },
  { unit: 4, en: 'P.E.', vi: 'thể dục', emoji: '⚽' },
  { unit: 4, en: 'Vietnamese', vi: 'tiếng Việt', emoji: '🇻🇳' },
  { unit: 4, en: 'schoolyard', vi: 'sân trường', emoji: '🏫' },
  { unit: 4, en: 'art room', vi: 'phòng mĩ thuật', emoji: '🖼️' },
  { unit: 4, en: 'computer room', vi: 'phòng máy tính', emoji: '💻' },
  { unit: 4, en: 'tiger', vi: 'con hổ', emoji: '🐯' },
  { unit: 4, en: 'umbrella', vi: 'cái ô / cây dù', emoji: '☂️' },
  { unit: 4, en: 'van', vi: 'xe tải nhỏ', emoji: '🚐' },

  // ── Unit 5: Beach & actions ──
  { unit: 5, en: 'read', vi: 'đọc sách', emoji: '📖' },
  { unit: 5, en: 'surf', vi: 'lướt sóng', emoji: '🏄' },
  { unit: 5, en: 'play with a ball', vi: 'chơi với quả bóng', emoji: '⛹️' },
  { unit: 5, en: 'go on a boat', vi: 'đi thuyền', emoji: '🚣' },
  { unit: 5, en: 'snorkel', vi: 'lặn với ống thở', emoji: '🤿' },
  { unit: 5, en: 'collect shells', vi: 'nhặt vỏ sò', emoji: '🐚' },
  { unit: 5, en: 'swimming', vi: 'bơi lội', emoji: '🏊' },
  { unit: 5, en: 'sitting', vi: 'ngồi', emoji: '🪑' },
  { unit: 5, en: 'running', vi: 'chạy', emoji: '🏃' },
  { unit: 5, en: 'web', vi: 'mạng nhện', emoji: '🕸️' },
  { unit: 5, en: 'window', vi: 'cửa sổ', emoji: '🪟' },
  { unit: 5, en: 'walk', vi: 'đi bộ', emoji: '🚶' },
  { unit: 5, en: 'box', vi: 'cái hộp', emoji: '📦' },
  { unit: 5, en: 'fox', vi: 'con cáo', emoji: '🦊' },
  { unit: 5, en: 'six', vi: 'số sáu', emoji: '6' },
  { unit: 5, en: 'wear a hat', vi: 'đội mũ', emoji: '👒' },
  { unit: 5, en: 'write in a notebook', vi: 'viết vào vở', emoji: '📝' },
  { unit: 5, en: 'eat a sandwich', vi: 'ăn bánh mì kẹp', emoji: '🥪' },
  { unit: 5, en: 'take a photo', vi: 'chụp ảnh', emoji: '📸' },
  { unit: 5, en: 'yo-yo', vi: 'cái yo-yo', emoji: '🪀' },
  { unit: 5, en: 'yogurt', vi: 'sữa chua', emoji: '🍨' },

  // ── Unit 6: Zoo animals ──
  { unit: 6, en: 'penguin', vi: 'chim cánh cụt', emoji: '🐧' },
  { unit: 6, en: 'kangaroo', vi: 'chuột túi', emoji: '🦘' },
  { unit: 6, en: 'camel', vi: 'lạc đà', emoji: '🐪' },
  { unit: 6, en: 'lizard', vi: 'thằn lằn', emoji: '🦎' },
  { unit: 6, en: 'crocodile', vi: 'cá sấu', emoji: '🐊' },
  { unit: 6, en: 'yellow', vi: 'màu vàng', emoji: '🟡' },
  { unit: 6, en: 'zebra', vi: 'ngựa vằn', emoji: '🦓' },
  { unit: 6, en: 'zoo', vi: 'sở thú', emoji: '🦁' },
  { unit: 6, en: 'zero', vi: 'số không', emoji: '0' },

  // ── Unit 7: Weather & outdoor fun ──
  { unit: 7, en: 'rainy', vi: 'trời mưa', emoji: '🌧️' },
  { unit: 7, en: 'windy', vi: 'trời có gió', emoji: '💨' },
  { unit: 7, en: 'hot', vi: 'nóng', emoji: '🥵' },
  { unit: 7, en: 'cold', vi: 'lạnh', emoji: '🥶' },
  { unit: 7, en: 'snowy', vi: 'trời có tuyết', emoji: '❄️' },
  { unit: 7, en: 'sunny', vi: 'trời nắng', emoji: '☀️' },
  { unit: 7, en: 'fly a kite', vi: 'thả diều', emoji: '🪁' },
  { unit: 7, en: 'make a snowman', vi: 'đắp người tuyết', emoji: '⛄' },
  { unit: 7, en: 'go outside', vi: 'ra ngoài', emoji: '🚪' },
  { unit: 7, en: 'ring', vi: 'cái nhẫn', emoji: '💍' },
  { unit: 7, en: 'bang', vi: 'tiếng nổ lớn', emoji: '🎆' },
  { unit: 7, en: 'long', vi: 'dài', emoji: '🦒' },
  { unit: 7, en: 'treasure', vi: 'kho báu', emoji: '💰' },
  { unit: 7, en: 'measure', vi: 'đo', emoji: '📏' },
  { unit: 7, en: 'explosion', vi: 'vụ nổ', emoji: '💥' },

  // ── Unit 8: Party & family ──
  { unit: 8, en: 'candy', vi: 'kẹo', emoji: '🍬' },
  { unit: 8, en: 'balloon', vi: 'bóng bay', emoji: '🎈' },
  { unit: 8, en: 'present', vi: 'món quà', emoji: '🎁' },
  { unit: 8, en: 'candle', vi: 'cây nến', emoji: '🕯️' },
  { unit: 8, en: 'neighbor', vi: 'hàng xóm', emoji: '🏘️' },
  { unit: 8, en: 'invite', vi: 'mời', emoji: '💌' },
  { unit: 8, en: 'gift card', vi: 'thẻ quà tặng', emoji: '💳' },
  { unit: 8, en: 'chocolate', vi: 'sô-cô-la', emoji: '🍫' },
  { unit: 8, en: 'father', vi: 'bố', emoji: '👨' },
  { unit: 8, en: 'brother', vi: 'anh / em trai', emoji: '👦' },
  { unit: 8, en: 'this', vi: 'này (ở gần)', emoji: '👇' },
  { unit: 8, en: 'that', vi: 'kia (ở xa)', emoji: '👉' },
  { unit: 8, en: 'three', vi: 'số ba', emoji: '3' },
  { unit: 8, en: 'throw', vi: 'ném', emoji: '🤾' },

  // ── Unit 9: Daily routines & time ──
  { unit: 9, en: 'get up', vi: 'thức dậy', emoji: '🛏️' },
  { unit: 9, en: 'have breakfast', vi: 'ăn sáng', emoji: '🥣' },
  { unit: 9, en: 'go to school', vi: 'đi học', emoji: '🎒' },
  { unit: 9, en: 'go home', vi: 'về nhà', emoji: '🏠' },
  { unit: 9, en: 'have dinner', vi: 'ăn tối', emoji: '🍽️' },
  { unit: 9, en: 'go to bed', vi: 'đi ngủ', emoji: '😴' },
  { unit: 9, en: 'two fifteen', vi: '2 giờ 15 phút (2:15)', emoji: '🕝' },
  { unit: 9, en: 'two thirty', vi: '2 giờ 30 phút (2:30)', emoji: '🕜' },
  { unit: 9, en: 'two forty-five', vi: '2 giờ 45 phút (2:45)', emoji: '🕑' },
  { unit: 9, en: 'flute', vi: 'cây sáo', emoji: '🪈' },
  { unit: 9, en: 'new', vi: 'mới', emoji: '👟' },
  { unit: 9, en: 'you', vi: 'bạn', emoji: '🫵' },
  { unit: 9, en: 'foot', vi: 'bàn chân', emoji: '🦶' },

  // ── Unit 10: Hobbies & things ──
  { unit: 10, en: 'read comics', vi: 'đọc truyện tranh', emoji: '📚' },
  { unit: 10, en: 'play chess', vi: 'chơi cờ', emoji: '♟️' },
  { unit: 10, en: 'fish', vi: 'câu cá', emoji: '🎣' },
  { unit: 10, en: 'play basketball', vi: 'chơi bóng rổ', emoji: '🏀' },
  { unit: 10, en: 'play volleyball', vi: 'chơi bóng chuyền', emoji: '🏐' },
  { unit: 10, en: 'play badminton', vi: 'chơi cầu lông', emoji: '🏸' },
  { unit: 10, en: 'horn', vi: 'cái kèn', emoji: '📯' },
  { unit: 10, en: 'corn', vi: 'bắp ngô', emoji: '🌽' },
  { unit: 10, en: 'storm', vi: 'cơn bão', emoji: '⛈️' },
  { unit: 10, en: 'car', vi: 'ô tô', emoji: '🚗' },
  { unit: 10, en: 'star', vi: 'ngôi sao', emoji: '⭐' },

  // ── Unit 11: Directions & places ──
  { unit: 11, en: 'next to', vi: 'bên cạnh', emoji: '🟦🔴' },
  { unit: 11, en: 'opposite', vi: 'đối diện', emoji: '🟦↔️🔴' },
  { unit: 11, en: 'between', vi: 'ở giữa', emoji: '🟦🔴🟦' },
  { unit: 11, en: 'turn left', vi: 'rẽ trái', emoji: '⬅️' },
  { unit: 11, en: 'turn right', vi: 'rẽ phải', emoji: '➡️' },
  { unit: 11, en: 'go straight', vi: 'đi thẳng', emoji: '⬆️' },
  { unit: 11, en: 'train station', vi: 'ga tàu', emoji: '🚉' },
  { unit: 11, en: 'bus station', vi: 'bến xe buýt', emoji: '🚌' },
  { unit: 11, en: 'supermarket', vi: 'siêu thị', emoji: '🛒' },

  // ── Unit 12: People & describing words ──
  { unit: 12, en: 'old', vi: 'già', emoji: '👴' },
  { unit: 12, en: 'young', vi: 'trẻ', emoji: '🧒' },
  { unit: 12, en: 'handsome', vi: 'đẹp trai', emoji: '🤵' },
  { unit: 12, en: 'pretty', vi: 'xinh đẹp', emoji: '🌸' },
  { unit: 12, en: 'germs', vi: 'vi trùng', emoji: '🦠' },
  { unit: 12, en: 'fern', vi: 'cây dương xỉ', emoji: '🌿' },
  { unit: 12, en: 'girl', vi: 'bé gái', emoji: '👧' },
  { unit: 12, en: 'bird', vi: 'con chim', emoji: '🐦' },
  { unit: 12, en: 'nurse', vi: 'y tá', emoji: '🧑‍⚕️' },
  { unit: 12, en: 'hurt', vi: 'bị đau', emoji: '🤕' },
  { unit: 12, en: 'cute', vi: 'dễ thương', emoji: '🥰' },
  { unit: 12, en: 'smart', vi: 'thông minh', emoji: '🧠' },
  { unit: 12, en: 'neat', vi: 'gọn gàng', emoji: '✨' },
  { unit: 12, en: 'messy', vi: 'bừa bộn', emoji: '🌀' },
  { unit: 12, en: 'floor', vi: 'sàn nhà', emoji: '🟫' },
  { unit: 12, en: 'eat', vi: 'ăn', emoji: '🍚' },
  { unit: 12, en: 'dream', vi: 'giấc mơ', emoji: '💭' },
  { unit: 12, en: 'green', vi: 'màu xanh lá', emoji: '🟢' },
  { unit: 12, en: 'sleep', vi: 'ngủ', emoji: '💤' },
  { unit: 12, en: 'spoon', vi: 'cái thìa', emoji: '🥄' },
];

if (typeof module !== 'undefined' && module.exports) { module.exports = { UNIT_WORDS }; }
